### ISSUE TITLE
”En god bog” bånd trin 2: Ændring af valgte kriterier-funktionalitet. Stemninger

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#10]
Ændring af valgte kriterier skal påvirke hvilke værker samt hvilke labels der vises i trin 1. #8 

Kun "stemnings"-kriterier har effekt.

**Comment by kfudbc** [comment]
Nu påvirker det hvilke labels der vises i trin1 - men det er kun dummy-værker der bliver vist

**Comment by KiraH** [comment]
testet OK
