### ISSUE TITLE
Bestilling af bøger - backend

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#100]
Der skal kunne bestilles en bog eller flere bøger (i en liste).
Det er ønsket at der der bestilles "uanset udgave". Det skal undersøges hvordan DÅP er sat op i forhold til dette.
Det er desuden en forudsætning at Adgangsplatformen returnerer et token, således at brugeren forbliver kendt inden for samme session. Se https://github.com/DBCDK/hejmdal/issues/404

Bestilte bøger skal opsamles i community servicen, se issue: https://github.com/DBCDK/content-first/issues/76

I grænsefladen skal være muligt at:
- Bestille en bog - https://github.com/DBCDK/content-first/issues/120
- Bestille alle bøger i huskelisten - https://github.com/DBCDK/content-first/issues/121
- Bestille alle bøger i en liste - https://github.com/DBCDK/content-first/issues/122
- Se hvilke bøger der er bestilt - https://github.com/DBCDK/content-first/issues/123

**Comment by rasmuserik** [comment]
#133 erstatter dette meta-issue
