### ISSUE TITLE
Søgning i Læsekompasset

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#102]
Skal groomes.

Hvordan skal søgning fungere i Læsekompasset?
Til 1. april er vi nødt til at bygge vores egen løsning. Senere kan OS måske bruges, hvis der kan begrænses på værker med den nye taksonomi og der kan leves op til Læsekompassets performance-krav.

Som minimum bør der kunne søges på forfatter og titler blandt værker i Metakompasset - men det forventes at der også kommer ønsker om at kunne søge på genre, stemningsord og andet.

Skal der bygges en solr med metakompas-værker og udvalg af metadata? Eller kan vi nøjes med andet.

**Comment by rasmuserik** [comment]
Et umiddelbart bud kunne være, blot at anvende den postgres, som vi allerede har kørende, - så vi ikke behøver at introducere nye komponenter.

**Comment by rasmuserik** [comment]
Jeg er i gang med at lave lidt prototype / kode-eksperimenter ifht. søgning, - tænker at dette også er en god måde for mig at komme ind i kodebasen :) Foreløbigt har jeg lavet et simpelt search-endpoint (hverken ranking eller indekser endnu). Koden ligger i følgende branch:

https://github.com/DBCDK/content-first/compare/102-search

**Comment by cboesgaard** [comment]
Et par ting at være opmærksomme på der vil dukke op: 

- rankering (nok ikke et problem til at begynde med, men hvis vi rammer 5k poster vil det blive relevant)

- stavefejl. 

Et par overvejelser om suggestions vil måske også være relevante, da det vil kunne afhjælpe stavefejl, men måske omvendt vil føre til at der opstår en solr et sted.

**Comment by KiraH** [comment]
testet OK
