### ISSUE TITLE
Det skal være muligt at hente en liste ud med id

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/content-first#105]
Endpoint til at hente en enkelt liste via id. Der er følgende scenarier:
* Hvis listen er privat og man ejer listen skal den returneres
* Hvis listen er privat om man ikke ejer listen, så skal man have besked om at listen er privat. 
* Hvis listen er offentlig skal den altid kunne returneres

**Comment by BettinaAndersen** [comment]
done
