### ISSUE TITLE
"Bibliotekaren anbefaler"-bånd trin 0

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#12]
På forsiden vises båndet "Bibliotekaren anbefaler". Her vises værker med forsider og beskrivelse for de værker, som er markeret med "Bibliotekaren anbefaler" i DB'en.

**Comment by kfudbc** [comment]
Selve båndet bliver nu vist i frontend - men der er kun indsat dummy-data - historien går derfor ud på at der skal hentes værker ud af backend. Jeg foreslår at listen af pid'er til at starte med er defineret i klient-delen, og dermed skal der være et endpoint der modtager en pid og giver et værk.

**Comment by KiraH** [comment]
testet OK
