### ISSUE TITLE
Bestille a̶l̶l̶e̶  bøger i en liste - Frontend

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#122]
Det skal være muligt at bestille alle bøger i en liste

**Comment by rasmuserik** [comment]
Efter snak med @AndersFriisBrodsgaard: bestilling af alle bøger i liste behøves ikke i denne omgang, men vi ønsker bestil-funktionalitet i kontekst-menuen ved listevisning og generelt (i.e. under `Husk | •••`).
