### ISSUE TITLE
flere bøger fra samme værk

### ISSUE THREAD

**Issue by KiraH** [DBCDK/content-first#129]
"Ekstremt højt & utrolig tæt på" ligger i metakompasset og content-first 2 gange med 2 pid'er. 

Kan vi gøre noget for at den kun vises 1 gang?

CBO: Jeg tror vi har work-id med når data beriges, så man kunne skifte til at bruge work id som identifier i data pipeline!?

Er det noget vi vil kigge nærmere på?

**Comment by cboesgaard** [comment]
Her er data vi har på de to værker, som har samme workid (work:838853):

% grep Safran exportWorks-2017-12-06.json
{"pid":"870970-basis:25792300","type":"Bog","items":259,"loans":2556,"pages":348,"title":"Ekstremt højt & utrolig tæt på","unitId":"unit:999748","workId":"work:838853","creator":"Jonathan Safran Foer","subject":"11. september, New York, sorg, 2000-2009, kærlighed, far-søn-forholdet","language":"Dansk","workType":"book","libraries":89,"titleFull":"Ekstremt højt & utrolig tæt på : roman","description":"Oscar mister sin far ved tvillingetårnenes kollaps i New York 11. september 2001. En efterladt nøgle sender ham rundt i byen for at finde låsen, der måske giver mere indsigt i farens liv","literaryForm":"romaner, fiktion","bibliographicRecordId":"25792300","cover":"https://metakompasset.demo.dbc.dk/api/cover/870970-basis:25792300","genre":""}
{"pid":"870970-basis:26296218","type":"Bog","items":99,"loans":927,"pages":348,"title":"Ekstremt højt & utrolig tæt på","unitId":"unit:1028928","workId":"work:838853","creator":"Jonathan Safran Foer","subject":"11. september, New York, sorg, 2000-2009, kærlighed, far-søn-forholdet","language":"Dansk","workType":"book","libraries":37,"titleFull":"Ekstremt højt & utrolig tæt på : roman","description":"Oscar mister sin far ved tvillingetårnenes kollaps i New York 11. september 2001. En efterladt nøgle sender ham rundt i byen for at finde låsen, der måske giver mere indsigt i farens liv","literaryForm":"romaner, fiktion","dateFirstEdition":"2005","bibliographicRecordId":"26296218","cover":"https://metakompasset.demo.dbc.dk/api/cover/870970-basis:26296218","genre":""}

**Comment by cboesgaard** [comment]
Den rigtige løsning er at arbejde med work-id hele vejen, så det fx også er i alle url'er og alternativt skal vi lave en mapning til en specific pid via work for alle værker.

**Comment by KiraH** [comment]
Umiddelbart mest stemning for den alternative løsning som CBO foreslår ovenfor.

**Comment by kfudbc** [comment]
Rettelser til metakompasset: https://github.com/DBCDK/metakompasset/issues/127
