### ISSUE TITLE
Modal(component) show-attribut?

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/content-first#139]
Hvordan bruges show-attributten på modal-komponenter, i.e.: den bliver givet med i [AddToListModal](https://github.com/DBCDK/content-first/blob/f68c11dfff3c6f988574216402b5bbe32ba6b7e5/src/client/components/modals/AddToListModal.container.js#L75) og [ShortListMergeModal](https://github.com/DBCDK/content-first/blob/f68c11dfff3c6f988574216402b5bbe32ba6b7e5/src/client/components/modals/ShortListMergeModal.container.js#L31), men findes så vidt jeg kan se ikke i [Modal.component](https://github.com/DBCDK/content-first/blob/master/src/client/components/modals/Modal.component.js)... er dette noget gammelt kode, der skulle være fjernet, eller overser jeg noget når jeg opretter en ny type modal?

**Comment by kfudbc** [comment]
Jeps, der mangler at blive ryddet op - show-attribut er ikke nødvendig længere
