### ISSUE TITLE
En god bog bånd: Trin 0 Forsidevisning

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#14]
På forsiden vises båndet "En god bog". Her vises værker med forsider og beskrivelse for de værker, som er valgt via kriterierne for "En god bog".

**Comment by kfudbc** [comment]
Båndet er lavet - men forbindelsen til backend mangler. Jeg tror dog at denne del laves i #10, derfor sætter jeg denne til fixed

**Comment by KiraH** [comment]
testet OK
