### ISSUE TITLE
Bestil-dialog/overlay

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/content-first#147]
Note: vi antager at vi har DÅP-token for indlogget bruger, hvilket ikke er tilfældet endnu.

- [x] implementer overlay design
- [x] fuldt bog objekt i stedet for pid, så vi ikke behøver at refaktorere state.
- [x] vis liste af materialer der skal bestilles
- [x] vis om de enkelte materialer kan bestilles (hent status fra DÅP)
- [x] vælg afhentningsbibliotek (hent liste af biblioteker fra DÅP)
- [x] klik for at udføre bestillingen
- [x] vis status for bestillingen
- [x] opdater den undeliggende logik for bestil-knapper til at åbne overlay.
- [x] enable bestil med openplatform-token
- [ ] ~~refaktorer: brug korrekte :x: :white_check_mark:  ikoner (afventer @AndersFriisBrodsgaard )~~
 - [x] unit tests

se #133 for design

**Comment by rasmuserik** [comment]
@AndersFriisBrodsgaard jeg tænker hvordan vi skal håndtere `Til afhentning på:` ved **status** for allerede bestilte materialer? Her giver det ikke rigtigt mening med en dropdown-menu: den kan ikke ændres, og ved bestilling af flere materialer, kan brugeren potentielt have bestilt materialerne til forskellige filialer.

Det enkleste vil være kun at have valg af filial, i bestillings-trinnet, og ikke i status-trinnet i overlay'et, da vi ellers også skal holde styr på hvor de enkelte materialer bestilles til, og afklare/implementere hvordan vi kommunikere dette til brugeren. I så fald synes jeg også, at vi skal flytte statusbeskeden i designet op til dér hvor valg af filial var før - frem fra under separator-linjen - da det giver bedre visuel balance i mine øjne.

**Comment by rasmuserik** [comment]
@AndersFriisBrodsgaard mht. ikonerne for `bestilt` / `fejl ved bestilling` og evt. spinner'en, er det så nogle som du lægger som svg i repositoriet? (Indtil da har jeg bare lagt det som tekst, hvor farven indikerer status).

Tænker også om vi ikke skal holde spinner-designet konsistent (forøjeblikket genbruger jeg blot den røde spinner, der også er andre steder i applikationen).

**Comment by AndersFriisBrodsgaard** [comment]
@rasmuserik det er ikke meningen, at vi skal implementere userstatus i denne fase. Tanken med at have en status på bestil-knappen er, at brugeren i den enkelte session kan se, hvilke bøger han lige har bestilt. 
I næste trin kan vi så lave en dybere implementation af userstatus, hvor vi også spørger biblioteket, hvilke bøger brugeren har bestilt og hvor de er i processen.
Giver det mening? Under alle omstændigheder kan vi lige drøfte det i morgen, så vi er helt på linie med, hvad grænsefladen skal kunne i denne omgang.

**Comment by AndersFriisBrodsgaard** [comment]
Mht. spinner, så brug bare den eksisterende, det er helt fint.

**Comment by rasmuserik** [comment]
@AndersFriisBrodsgaard - jeg er helt med på, at vi ikke skal implementere userstatus  - kan se at jeg havde formuleret mig lidt klodset. 

I de nederste wireframes i #133, vises status for bestillingerne, hvori der er en dropdown hvor man kan vælge "`Til afhentning på:'". Det var denne jeg mente med `Til afhentning på`, og ikke at vi skulle hent userstatus :) Spørgsmålet var, hvad der skal gøres med den dropdown, - da den virker lidt forvirrende i interaktionsflow'et, (hvis en bruger åbner en bestilling der er allerede er lavet eller ikke kan lade sig gøre, kommer den direkte til status-delen af bestilling, hvor dropdown'en får det til at se ud som om at de tidligere bestillinger er sendt til en given filial, hvilket på ingen måde er sikkert, så det enkleste ville være at skære den væk) - anyway, vi kan kigge på det i morgen.

**Comment by AndersFriisBrodsgaard** [comment]
OK, tror at jeg forstår nu :-)
Hvis man allerede har foretaget en bestilling af en bog, som ligger i huskelisten og man så derefter vælger "Bestil alle i listen" - hvordan skal den så præsenteres i overlayet. Det er det, der er problemet, ikke? Det er en god pointe. 
Umiddelbart er der to muligheder: at udelade den, som du foreslår, eller at gøre den inaktiv/grå. 
Det nemmeste er jo nok at udelade den, så lad os prøve det og se, hvordan brugerne reagerer på det.

**Comment by KiraH** [comment]
OK
