### ISSUE TITLE
log hvilke værksider en bruger besøger

### ISSUE THREAD

**Issue by KiraH** [DBCDK/content-first#154]
Det ønskes at kunne logge fra frontend til elk'en.

På sigt skal denne kunne fungere sammen med #76

**Comment by rasmuserik** [comment]
Vi kan vel også logge bestillinger på samme vis.

**Comment by rasmuserik** [comment]
Jeg savner lidt denne nu, da jeg sidder og implementerer availability på værkniveau, - og det ville være rart at kunne logge fejl i disse til elk'en... tilføjer en `// TODO...` note i koden i `order.middelware.js`, hvor der mangler logning / kunne være rart at logge.

**Comment by BettinaAndersen** [comment]
Tages med i nuværende sprint (uge 5-7).

**Comment by KiraH** [comment]
testet OK
