### ISSUE TITLE
Modal om at brugeren skal logge ind

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/content-first#159]
Skal bruges ved bestil-knap, huskeliste, etc.

@AndersFriisBrodsgaard har/vedhæfter design. Baseres på eksisterende smalle modal.

**Comment by AndersFriisBrodsgaard** [comment]
Design af modal her:
![overlay-log-ind-for-at-bestille](https://user-images.githubusercontent.com/18284484/35335757-b985bf3c-0116-11e8-9cf2-d996e0954575.png)

**Comment by KiraH** [comment]
testet OK
