### ISSUE TITLE
Pipeline

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#16]
Der skal oprettes jobs og pipeline i jenkins til udrulning og tests.

**Comment by jpsecher** [comment]
Vi skal nok have kigget nærmere på hvordan en [React webapp indsættes i production](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment), mere præcist, hvornår og af hvem skal `npm run build` køres, og hvor skal resultatet gemmes.
