### ISSUE TITLE
Luk modal dialog, ved klik udenfor denne

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/content-first#160]
@AndersFriisBrodsgaard: oprettet her, som vi snakkede om

Note: kildekoden til modal-dialog'en ligger i `src/client/components/modals/Modal.component.js`.

**Comment by AndersFriisBrodsgaard** [comment]
Jeps, generelt skal det være muligt at lukke alle modalvinduer ved at klikke i det mørke område omkring modalen, ligesom ved klik på luk-krydset i øverste højre hjørne.

**Comment by KiraH** [comment]
testet OK
