### ISSUE TITLE
Profilsiden v2

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#173]
Profilsiden skal opdateres efter design.

Brugernavn og brugerfoto skal vises. Se #183 og #184

**Lister:**
Det skal være muligt at se allerede oprettede lister.
Det skal være muligt at oprette en ny liste.

**Comment by KiraH** [comment]
Der mangler mouseover "hånden" når man fører musen over profilbilledet øverst til højre.

**Comment by KiraH** [comment]
testet OK
