### ISSUE TITLE
Bestil-dialog ikoner

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/content-first#175]
refaktorer: brug korrekte ikoner for  :x: :white_check_mark:  

- [ ] design og tilføjelse af svg-ikoner til repos (@AndersFriisBrodsgaard)
- [ ] Brug af ikonerne i bestil-dialogen

se #147

**Comment by BettinaAndersen** [comment]
Bør udvides til samlet løsning for håndtering af ikoner.

**Comment by AndersFriisBrodsgaard** [comment]
Ikke længere relevant, da der laves et helt nyt design incl stil for ikoner.
