### ISSUE TITLE
Udtræk af forfatterliste fra Metakompasset

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#176]
For at kunne finde så mange forfatterbilleder som muligt - og navngive dem korrekt er der brug for et udtræk af navne fra Metakompasset

**Comment by vibjerg** [comment]
Her er et udtræk fra http://metakompas-p01.dbc.dk:8001/api/exportWorks dags dato: 

(Vi kan overveje at lave et endpoint til det, kan laves på ganske kort tid)

Agatha Christie
Agnes Ravatn (f. 1983)
Alaa Al Aswany
Alain De Botton
Alan Moore
Alden Bell
Alexander McCall Smith
Ali Smith
Anders Matthesen
Andrej Kurkov
Andrew Wilson (f. 1967)
André Brink
Anna Dyhr
Anna Gavalda
Anne Bredahl (f. 1971)
Anne Lise Marstrand-Jørgensen
Anne Mette Hancock
Anne-Cathrine Riebnitzsky
Barry Lyga
Bent Vinn Nielsen
Bernard Cornwell
Birgithe Kosović
Bjarne Reuter
Bjørn Rasmussen (f. 1983)
Britt Karin Larsen (f. 1945)
C. L. Taylor
Camilla Stockmann
Caroline Albertine Minor
Carsten Jensen (f. 1952)
Caspar Eric (f. 1987)
Cecelia Ahern
Charles Bukowski
Cheryl Strayed
Chil Rajchman
Chimamanda Ngozi Adichie
Chris Carter
Chris Cleave
Christian Kracht
Christopher Paolini
Claus Høxbroe
Colleen Hoover
Dan Brown
Dan Simmons
Daniel Kehlmann
Dea Trier Mørch
Ditte Wiese (f. 1978)
E. L. Doctorow
E. O. Chirovici
Edward St. Aubyn
Elle Kennedy
Erik Valeur
Erin Morgenstern
Erlend Loe
F. M. Dostojevskij
Frances Hardinge
Frank Herbert
Frank McCourt
Frank Miller
Fredrik Backman
Gabrielle Zevin (f. 1977)
Gard Sveen
Geir Gulliksen
George R. R. Martin
Georges Perec
Georgette Heyer
Georgi Gospodinov
Gianrico Carofiglio
Gillian Flynn
Gunnar Stꜳlesen
Gustave Flaubert
Hans Kirk (f. 1898)
Hanya Yanagihara (f. 1974)
Haruki Murakami
Helen Fielding
Helga Flatland
Helle Helle
Herman Melville
Hermann Ungar (f. 1893)
Herta Müller
Heðin Brú
Håkan Nesser
Ib Michael
Iben Mondrup
Ingar Johnsrud
Inger Christensen (f. 1935)
J. M. Coetzee
J. R. R. Tolkien
Jakob Ejersbo
James Dashner
Jan Guillou
Jan Sonnergꜳrd
Jane Austen
Jean-Paul Didierlaurent
Jeannette Walls
Jenny Colgan (f. 1972)
Jens Blendstrup
Jesper Stein
Jette A. Kꜳrsbøl
Jo Nesbø
Joanne K. Rowling
Joe Abercrombie
Johan F. Krarup
Johannes Anyuru
John Flanagan
John Steinbeck
John Williams (f. 1922)
Jojo Moyes
Jonas T. Bengtsson
Jonathan Franzen
Jonathan Littell
Jonathan Safran Foer
Jonathan Tropper (f. 1970)
Josefine Klougart
Judith Hermann (f. 1970)
Juli Zeh
Julia Heaberlin
Julian Barnes
Jørn Riel
Kamilla Hega Holst
Kaori Ekuni
Katja Kettu
Katrine Marie Guldager
Katy Colins
Kelly Rimmer
Ken Follett
Kent Haruf (f. 1943)
Kim Leine
Kirsten Myers
Kirsten Thorup
Kjell Westö
Kjersti Annesdatter Skomsvold (f. 1979)
Knud A. Petersen
Kristian Bang Foss
Kristina Stoltz
Kristina Ꜳmand
Kristoffer Jacob Andersen
Kurt Aust
Lars Mytting
Laura Barnett (f. 1982)
Laura Ingalls Wilder
Lauri Ahonen
Lee Child
Leif G. W. Persson
Lena Dunham
Lene Kꜳberbøl
Leonie Swann
Leonora Christina Skov
Lesley Pearse
Liselotte Michelsen
Lone Aburas (f. 1979)
Lone Hørslev
Lone Mikkelsen (f. 1954)
Lori Nelson Spielman
Lotte Hammer
Lucinda Riley
Luke Rhinehart
Lyndsay Faye
M. de Cervantes Saavedra
Madame Nielsen (f. 1963)
Malene Sølvsten
Manfred Gregor
Maren Uthaug
Margaret Atwood
Maria Gerhardt (f. 1978)
Maria Helleberg
Maria Semple (f. 1964)
Marian Keyes
Marilynne Robinson
Marina Lewycka
Marjane Satrapi
Martin Jensen (f. 1946)
Merete Pryds Helle
Mette Finderup
Mhairi McFarlane (f. 1976)
Michael Chabon
Michael Robak (f. 1969)
Michel Bussi (f. 1965)
Michel Faber
Mika Waltari
Milan Kundera
Morten Brask
Morten Sabroe
Naja Marie Aidt
Natasha Illum Berg
Natasha Pulley
Nathan Hill
Nathaniel Hawthorne
Neal Asher
Neil Gaiman
Nick Lake
Nicola Yoon
Nicole Boyle Rødtnes
Nicole Krauss
Niels Lyngsø
Nina George
Olav Hergel
Olivier Bourdeaut (f. 1980)
Orhan Pamuk
Patrick Flanery
Patrick Modiano
Paul Auster
Peter Høeg (f. 1957-05-17)
Peter-Clement Woetmann
Philip K. Dick
Philip Pullman
Philipp Meyer (f. 1974)
Pierre Lemaitre (f. 1951)
Rainbow Rowell (f. 1973)
Ransom Riggs
Rosa Liksom
Rune Christiansen (f. 1963)
Ruth Ware (f. 1977)
Ryu Murakami
Salman Rushdie
Samanta Schweblin
Shari Lapena
Sidsel Falsig Pedersen
Siegfried Lenz
Signe Maxen
Simon Fruelund
Siri Hustvedt
Sissel-Jo Gazan
Sofi Oksanen
Sophie Kinsella
Stanislaw Lem
Stephen King (f. 1947)
Stig Dalager
Stine Pilgꜳrd
Svend Åge Madsen (f. 1939)
Søren Kierkegꜳrd
Thomas Mann
Torben Munksgꜳrd
Tove Ditlevsen
Trisse Gejl
Trude Marstein
Umberto Eco
Vigdis Hjorth
Virginia Bergin
Virginia Woolf
Vita Andersen (f. 1944)
William Gibson
Wladimir Kaminer (f. 1967)
Zadie Smith
al-Tayyib Sālih
Åsne Seierstad

**Comment by BettinaAndersen** [comment]
Done
