### ISSUE TITLE
Upload og skalering af billeder

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/content-first#177]
Det skal være muligt at uploade et billede fra klienten. Billedet skal skaleres i X forskellige størrelser (defineres af @AndersFriisBrodsgaard). Klienten skal have et objekt retur med link til de forskellige størrelser.  

- [x] Offentlig endpoint til upload af billeder (POST /v1/image/)
- [x] POST Endpoint skal kun være tilgængeligt, hvis man er logget ind.
- [x] Offentlig endpoint til hente billeder (GET /v1/image/[id]) (Bruges allerede til at forsidebilleder)
- [x] Mulighed for at hente en skaleret version af billedet (GET /v1/image/[id]/width/height)
- [x] Cache af skalerede billeder.

**Comment by KiraH** [comment]
OK
