### ISSUE TITLE
Availability/bestil på værk-niveau.

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/content-first#178]
Når vi tjekker for availability / bestiller givet pid, skal vi tjekke for samlet availability for samtlige manifestationer i værket, og returnere om mindst et er tilgængligt. Ligeledes skal bestillingen blot være et af manifestationerne i værket.

- [x] Kald availability for samtlige materialer i ~~værket~~ underværket
    - [x] ~~værket~~ underværket (kun bøger)
- [x] Endpoint til at hente anonymt openplatform-token (nogle materialer findes ikke med søgeprofil fra biblioteksspecifikke token)
- [ ] Fejlhåndtering ved timeout på work/availability.
    - [x] retry et antal gange
    - [ ] resultat fra undeliggende service (forkert i visse tilfælde?)?
- [x] husk anonymt openplatform-token
- [x] Bestilling sendes på samtlige materialer i underværket
- [x] refaktorering

Kunne det eventuelt give mening at DÅP udvides med denne funktionalitet, i stedet for kun, at implementere den i content-first?

**Comment by KiraH** [comment]
OK
