### ISSUE TITLE
Meta-list-data

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#180]
Det skal være muligt at hive følgende data ud sammen med lister
- ~~Tidsstempler (created  og modified)~~
- Profildata for den der har oprettet listen (billede og navn)
- Ved visning af lister skal der vises brugernavn og billede for hver liste.

Profildata vises på listebånd i på forsiden og på visning af lister.

**Comment by BettinaAndersen** [comment]
Forbundet med #213

**Comment by vibjerg** [comment]
afventer #226
