### ISSUE TITLE
Opret Profil-side

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#183]
Første gang brugeren logger ind skal der oprettes et brugernavn og være mulighed for oprettelse af billede. Hvis intet billede uploades benyttes et dummy-image.
Der skal desuden være en tekst som brugeren skal acceptere (ved hak i en checkboks), hvor brugeren informeres om hvad vi bruger hans data til samt at brugeren skal have rettighedder til det han deler.

Mulighed for at redigere og slette profil er i første omgang nice-to-haves

- [x] Opret profilside skal være uden header
- [x] Mulighed for at uploade/ændre profilbillede
- [x] Beskrivende fejlbesked, hvis man forsøger at uploade et ugyldigt billede. 
- [x] Inputfelt til navn 
- [x] Checkboks til consent
- [x] Hente information om hvilket bibliotek man er logget ind via. 
- [x] Placeholder til concent-text
- [x] Gemme informationer i databasen.
- [x] Hente informationer ud, når man logger ind (Billede skal vises i topbar)
- [x] Hvis man logger ind uden en oprettet profil, skal man sendes til profil/opret
- [x] Redirect til forside, når profil er oprettet
- [x] håndtér update errors

**Comment by KiraH** [comment]
testet OK
