### ISSUE TITLE
DESIGN: Opret profil-side

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#184]
Første gang brugeren logger ind skal der oprettes et brugernavn og være mulighed for oprettelse af billede. Hvis intet billede uploades benyttes et dummy-image.
Der skal desuden være en tekst som brugeren skal acceptere (ved hak i en checkboks), hvor brugeren informeres om hvad vi bruger hans data til samt at brugeren skal have rettighedder til det han deler.

Mulighed for at redigere og slette profil er i første omgang nice-to-haves.

Afhængighed til udvikler-issue: #183

**Comment by KiraH** [comment]
OK
