### ISSUE TITLE
Udtræk af loancount

### ISSUE THREAD

**Issue by kfudbc** [DBCDK/content-first#19]
Vi skal have mappet loan count til de pid'er som er inddateret i metakompasset

**Comment by cboesgaard** [comment]
Der er lavet et hurtigt hack for at projektet kan rykke videre. Men det kan ikke rigtig lukkes/komme i mål før vi ved hvordan vi godt vil have data pipeline til at fungere. Jeg forestiller mig et jenkinsjob? Måske skal det i så fald kører på xp-build-i01 -- da det er eneste maskine der har opdaterede loancounts!?

**Comment by BettinaAndersen** [comment]
Brug berigelses-script til at hente data fra ADHL-SOLR.
