### ISSUE TITLE
Max-begrænsning på bestilling af bøger

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#197]
Vi skal have indført et max antal på bøger på 10 bøger der kan bestilles samtidig. Der skal desuden tænkes design på dette.

Er der andet end en teknisk begrænsning? Hvem har evt. en holdning til hvor mange bøger der må bestilles på en gang.

Man kunne også sætte en advarsel på, hvis brugeren forsøger at bestille mere end et vist antal på en gang.

Eller grænse på hvor mange der bestilles.

**Comment by rasmuserik** [comment]
Splittet op i #371, #372, #373

**Comment by KiraH** [comment]
Man kan kun bestille den øverste del af listen. Hvis man klikker på "bestil hele listen" igen som der står man skal, får man at vide at alle bøgerne allerede er bestilt.

**Comment by rasmuserik** [comment]
Hmm, jeg må have lavet en fejl, jeg kigger på det! :)

**Comment by rasmuserik** [comment]
Så er fixet i master,
og skulle rulle ind
på staging om lidt :)

**Comment by KiraH** [comment]
Jeps, nu virker det.
