### ISSUE TITLE
Opret database med tabeller i henhold til skema på tavlen

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#2]
Værker med den nye taksonomi fra Metakompasset skal kobles med yderligere info fra Brønden; forfatter, titel, emneord, forside, beskrivelse, sidetal. Der skal derudover tilføjes et felt som indikere om værket er "anbefalet af bibliotekaren".

**Comment by kfudbc** [comment]
evt med knex-migrationer

**Comment by cboesgaard** [comment]
Nu er der noget data der kan tages udgangspunkt i. Det er de pid'er der p.t. er i metakompas, kørt gennem Finns og mine scripts.
http://metode.dbc.dk/~cbo/content-first/all-info.json
De billeder der lå der i 500pix ligger i samme katalog, navngivet efter pid.

**Comment by KiraH** [comment]
Der skal sikkert løbende laves ændringer i databasen, men nu lukkes denne.
