### ISSUE TITLE
Generisk `/object`-endpoint til listeelementer og kommentarer

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/content-first#201]
> Med introduktionen af åbne og sociale lister, bliver vi nødt til at tilpasse /lists endpoints til at kunne tage imod enkelte elementer til en liste. 

Opdateret af RasmusErik:

Vi talte om at  lave et generelt `/object` endpoint, som giver mulighed for at implementere funktionalitet til oprettelse og redigering af lister i grænsefladen.

Tasks:

- [x] dokumentation af design, implementationsdetaljer (hvorledes indeks for performance when needed), etc. (missing community-service transactional)
- [x] [specifikation af endpoints](https://github.com/DBCDK/content-first/blob/201-list-api/doc/endpoints.md#generic-objects)
- [x] unit tests
- [x] integration test for typical flow (and link to it as example from documentation)
- [x] post/put object
- [x] get object
- [x] find objects
- [x] opdatere find, så det også understøtter key+owner forespørgsler (samt opdatere dokumentation)
- [x] opdatere find/get og dokumentation så vi får created/modified-date med ud. + opdater api, så alle særlige attributter starter med `_`
- [x] resultatet skal være `_id`, `_rev`, i stedet for `ok`, `id`, `rev`

----
Gamle noter, erstattet af ovenstående:

> **Åbne lister**
> På nuværende tidspunkt skal man sende hele listen afsted for at opdatere den, og det vil give problemer, når flere brugere kan redigere en liste. Vi har derfor brug for at skille tilføjelse af elementer på en liste ud i særskilte endpoints. 
> 
> Forslag til endpoints:
> 
> - POST /lists -> Opretter en liste
> - PUT /lists/{listId} -> Redigerer listeinformation
> - POST /lists/{listId} -> tilføjer et element til listen
> - PUT /lists/{listId}/{elementId} -> rediger et element til listen
> - GET /lists/{listId} -> Henter en liste
> - DELETE /lists/{listId} -> Sletter en liste og alle elementer i listen
> - DELETE /lists/{listId}/{elementId} -> sletter element i listen
> 
> Brugeren der har oprettet listen kan: 
> - kan også redigere og slette listen. 
> - Kan redigere og slette egne elementer på listen
> - Kan slette andres elementer på listen. 
> 
> Brugere som ikke har oprettet listen kan:
> - Tilføje elementer på listen
> - Slette og redigere egne elementer på listen
> 
> Det skal overvejes om listeelementer skal udskilles som adskilte relaterede objekter i communityServicen. 
> 
> Når man opretter en liste kan man sortere rækkefølgen af elementer. Hvordan løser vi det med den nye struktur?
> 
> **Sociale Lister** (Kan flyttes til nyt issue)
> Sociale lister giver mulighed for at kunne kommentere på en liste. Og kunne indeholde følgende endpoints:
> 
> - POST /comments/{listId} -> Tilføj kommentar til liste
> - POST /comments/{listId}/{elementId} -> Tilføj kommentar til element på listen
> - GET /comments/{listId} -> hent kommentarer til liste (med mulighed for paginering)
> - GET /comments/{listId}/{elementId} -> hent kommentarer til element på liste. (med mulighed for  paginering)
> 
> Der er i første omgang ikke mulighed for at slette og redigere kommentarer.

**Comment by rasmuserik** [comment]
Som vi talte om: Hvis vi har CRUD for generiske objekter, vil dette dække størstedelen af funktionaliteten herover, - og det vil være lettere at tilføje yderligere funktionalitet i front-end'en uden at skulle opdatere backend'en. Jeg laver et udkast til spec i `doc/`, og implementerer det derefter.

**Comment by vibjerg** [comment]
Vi har ofte brug for at man kan hive noget profil information ud sammen med et objekt, f.eks. navn og billede. Kunne det være en idé at ændre owner til et objekt med strukturen 
```
{
   id: 'attributes.openplatform_id',
   image: 'attributes.image',
   name: 'name'
}
```

Det tænker jeg at gøre ifb. med #180

**Comment by vibjerg** [comment]
Alternativt kan vi tilføje en profile property til retur objektet.

**Comment by rasmuserik** [comment]
I mine øjne, hører profilinformationer ikke hjemme på de enkelte kommentarobjekter, men bør hentes separat. I.e. samme profil vil typisk optræde på flere kommentarer, og så derfor giver det mening hvis vi kun sender profil-id'et med fra kommentar'en, og profil-informationerne sendes separat.

Ville også foreslå at vi har ét sted i redux-state'en hvor vi gemmer profiler, så hver profil kun behøves læses første gang vi støder på den.

**Comment by vibjerg** [comment]
Da der allerede findes et endpoint til at hente profildata ud med, synes jeg vi skal gøre som du foreslår og hente info via grænsefladen og holde informationerne i redux

**Comment by vibjerg** [comment]
Det skal gerne være muligt at få created_date og modified_date ud med objektet, skal f.eks. bruges til at vise hvornår en kommentar oprettet/redigeret.

**Comment by vibjerg** [comment]
Når man opretter et nyt objekt får man f.eks. følgende retur: 
```
{
  "data": {
    "ok": true,
    "id": "c034c570-1b8e-11e8-8182-cbff755f56b5",
    "rev": "1519716055879-2i3umbzovmf"
  }
}
```

Og når man henter der ud igen, får man:

```
{
  "data": {
    "_key": "2737b8d4-c575-4703-8441-ac9053d34d86",
    "_type": "comment",
    "_public": true,
    "comment": "bummelummelumme",
    "_id": "c034c570-1b8e-11e8-8182-cbff755f56b5",
    "_rev": "1519716055879-2i3umbzovmf",
    "_owner": "zmdiaqHdfyGjxICzC/T/PjjBQKbXGdIK",
    "_created": 1519716058,
    "_modified": 1519716058
  }
}
```

Det ville være rart som minimum at nøglerne hedder det samme id => _id og rev => _rev. Derudover ville det så give mening at returnere det fulde object retur ved oprettelse?

**Comment by rasmuserik** [comment]
Navnene `ok`,`rev` og `id`, var baseret på, at lade APIet følge de forskellige couch-implementationer i stedet for at opfinde et nyt api. Enig i at det giver god mening blot at returnere `{_rev:.., _id:..}` så det gør vi.

**Comment by KiraH** [comment]
done
