### ISSUE TITLE
 De kendtes bogreol

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#202]
- Størrelsesmæssigt skal det passe til en ipad-skærm (og browser).

- Ved klik på hostspot vises detaljer om bogen som overlay.
- ”puls” for at vise brugeren, hvor man kan klikke. Hvis man har klikket på en bog skal der være en svag markering af de andre klikbare områder.

**Comment by BettinaAndersen** [comment]
Ny story på indholds-delen er oprettet #218

**Comment by KiraH** [comment]
testet OK
