### ISSUE TITLE
Tilføjelse af bog til en åben liste

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#204]
- I listevisning skal brugere kunne klikke på "Tilføj bog til listen".
- Man skal kunne søge en bog frem fra content-first basen (Man bør kunne genbruge funktionaliteten fra opret liste)
- Man skal kunne tilføje en beskrivelse til bogen
- Man skal kunne redigere i beskrivelsen til bogen.
- Ønsket er at den der har tilføjet en bog skal kunne redigere beskrivelsen og  fjerne bogen. 
- Ejeren af listen skal blot kunne fjerne bøger tilføjet af andre, men kan ikke redigere beskrivelsen. Heller ikke på redigeringssiden
- Ejeren af listen kan ændre i rækkefølgen på redigeringssiden. 

**API**
Skal der benyttes PUT /LIST/{uuid} eller POST /object for at tilføje en bog til en liste?  
- https://github.com/DBCDK/content-first/blob/201-list-api/doc/endpoints.md#post-object-or-put-objectid
- https://github.com/DBCDK/content-first/blob/201-list-api/doc/endpoints.md#put-v1listsuuid

**Comment by KiraH** [comment]
testet OK
