### ISSUE TITLE
Oprettelse af liste: åbne og sociale lister

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#205]
Ved oprettelse af en liste skal der ud over offentlig og privat også kunne vælges om listen skal være social og/eller åben.

Der findes allerede et flag, public, på en liste som kan være true/false. Der kan tilføjes social op open på samme vis. 

Accept:

- Når man går ind på en liste er der 3 bokse i bunden af listen, hvor man kan vælge om listen skal være offentlig, åben og/eller social.

**Comment by KiraH** [comment]
testet OK.
