### ISSUE TITLE
DESIGN: Sociale lister

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#207]
Det skal være muligt at kommentere en liste samt enkelte værker i listen.
Nyeste kommentar præsenteres, men skal optræde kronologisk, hvis der klikkes på ”Vis alle/flere”
Der må gerne kunne benyttes emojis,  linjeskift,  og link. Dette skal specificeres yderligere. Billeder bliver ikke muligt nu.
Der skal skrives hvornår kommentaren er givet (1 time, 2 dage osv.).
Evt. startes med kommentarer til simple-lister (ikke visuelle).

Udvikler story: #203

**Comment by AndersFriisBrodsgaard** [comment]
Samme design som til visuel liste, hvor der vises kommentarer

![visuel-liste-se kommentarer-til-post](https://user-images.githubusercontent.com/18284484/37572311-7b67f63a-2b09-11e8-92c1-2e72e9b60296.png)
