### ISSUE TITLE
Brug af recommenderen på filtersiden 

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#209]
Resultatet på filtervisningssiden, eksempelvis https://content-first.demo.dbc.dk/en-god-bog, skal ændres så recommenderen benyttes i stedet for nuværende filtrering på tags.
Samtidig skal mulighed for sortering fjernes.

**Recommender url:** 
http://0.recompass-service.search.prod.mcp1.dbc.dk/recompass/help

**Comment by kfudbc** [comment]
Bånd på forsiden bruger også recommender

**Comment by KiraH** [comment]
testet OK
