### ISSUE TITLE
Understøttelse af objekt-referencer som listeelementer.

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/content-first#217]
Implementeres ved, at vi opdaterer frontend-koden, så listerne gemmes som generiske objekter. Ved samme lejlighed kan vi eventuelt lave nogle små refaktoreringer af liste-delen af state'en, i stil med #237 

- [x] lists just data, not links
- [x] ændr hentning af lister, så den både henter dem som generiske objekter, og fra det gamle liste-endpoint, (eller afklar om vi skal bevare gamle lister)
- [x] opdater gemning af lister, så de gemmes i det generiske objekt endpoint
- [x] gennemgå indlæste data, og indlæs objekt hvis `_id` er tilstede. Gem kun `_id` for elementer i liste. 
- [x] søg efter liste-entries hvis open-list

---

Lister skal kunne understøtte at listeelementer er objekt-referencer (uuid til objekt i `/object` endpointet).
Lister skal også have en ~~`openlist`~~ `writable` option, og mulighed for at blackliste elementer (så ejeren af listen kan slette/blackliste elementer som listeejeren ikke ejer).

Relateret til #201

**Comment by rasmuserik** [comment]
Alternativt kunne vi opdatere frontend-koden, så listerne gemmes som generiske objekter, i stedet for at have et specialiseret endpoint. Dette vil også gøre det lettere at tilføje ekstra liste-funktionalitet senere hen.

**Comment by BettinaAndersen** [comment]
Er i brug
