### ISSUE TITLE
Tilføjelse af kommentarer til element i en social liste

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#219]
- Det skal være muligt at kommentere elementerne i en liste.
- Nyeste kommentar (1 el. 2) præsenteres, men skal optræde kronologisk, hvis der klikkes på ”Vis alle”
- Der skal skrives hvornår kommentaren er givet (1 time, 2 dage osv.).
- I denne version er der kun kommentarer til simple-lister (ikke visuelle).

API
Tilføjelse af kommentarer sker gennem det generiske object endpoint:
https://github.com/DBCDK/content-first/blob/201-list-api/doc/endpoints.md#post-object-or-put-objectid

Skal i denne version ikke understøtte:
- Billeder og video

Se også #203

**Comment by KiraH** [comment]
Hvis man ikke er logget ind kan man stadig skrive i kommentarfelterne.

**Comment by KiraH** [comment]
Testet OK
