### ISSUE TITLE
script der henter billeder

### ISSUE THREAD

**Issue by cboesgaard** [DBCDK/content-first#22]
Vi har et script der giver os json-linjer, hvori der findes links til billeder som har en begrænset levetid.

**Vi mangler lige at afklare hvilke størrelser der er relevante.**

Vi skal have et script der læser sådanne linjer, checker i en cache (filsystem eller direkte til db) om billedet til den pågældende pid findes og ellers henter det. Eksempel på json:

{"pid":"870970-basis:53188931","unitId":"unit:22125672","workId":"work:20137979","bibliographicRecordId":"53188931","creator":"Jens Blendstrup","title":"Havelågebogen","titleFull":"Havelågebogen : trælåger, gitterlåger, fyldningslåger, jern- og smedejernslåger","type":"Bog","workType":"book","language":"Dansk","items":102,"libraries":42,"pages":119,"image_detail_117":"https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=53188931&attachment_type=forside_117&bibliotek=870970&source_id=870970&key=d64ecdf251953fd2363a","image_detail_207":"https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=53188931&attachment_type=forside_207&bibliotek=870970&source_id=870970&key=ec106f133134ff396563","image_detail_42":"https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=53188931&attachment_type=forside_42&bibliotek=870970&source_id=870970&key=be4ff0b00f6848dd4d8d","image_detail_500":"https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=53188931&attachment_type=forside_500&bibliotek=870970&source_id=870970&key=64c340098547947dfe65","image_thumbnail":"https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=53188931&attachment_type=forside_lille&bibliotek=870970&source_id=870970&key=1ac13015a17a20b514a3","image_detail":"https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=53188931&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=166ecf801b757098902a"}

**Comment by cboesgaard** [comment]
Til eget brug har jeg lavet et python script der laver curl linjer til at hente 500pix billeder, sig til hvis det kan bruges til noget.

**Comment by BettinaAndersen** [comment]
Super fin
