### ISSUE TITLE
Seneste offentlige lister skal også vises på forsiden, når man ikke er logget ind

### ISSUE THREAD

**Issue by kfudbc** [DBCDK/content-first#251]
1. fetchUser i requester.js kalder ikke sin callback funktion når bruger ikke er logget ind. Dermed bliver recent lists ikke hentet ud.
2. der bruges nyt object endpoint til at hente seneste lister - så lister der er lavet før dette bliver vist ikke hevet ud. det er vel ok?

**Comment by rasmuserik** [comment]
Angående 2) antog jeg at det var ok, da jeg implementerede det, - da nyeste lister alligevel bliver vist først, så det kun er en kort transitionsperiode hvor der er nogle lister der ikke bliver vist.

Jeg får ikke kigget på 1) her og nu, da jeg ikke regner med at sidde med kode i dag, men der lyder til at du har overblik over hvad fejlen er, og er velkommen til at rette den. Ellers, hvis det kan vente til jeg er på DBC igen, er du også velkomment til at assigne den til mig.

**Comment by kfudbc** [comment]
det lyder rimeligt med 2). Jeg laver lige et fix til 1)
