### ISSUE TITLE
Brug af recommender på værk-siden

### ISSUE THREAD

**Issue by kfudbc** [DBCDK/content-first#252]
Recommenderen kan benyttes til båndet "Bøger der giver lignende oplevelser". Da recompass tager tags som input og ikke pid'er, skal man bruge de tags der er tilknyttet værket.

Værksiden skal spørge recompas om anbefalinger på baggrund af de tags værket har.

Accept:
Der skal være anbefalinger baseret på værkets tags - 20 anbefalinger.

**Comment by kfudbc** [comment]
Løsningsforslag (rettelser i WorkPage.container.js)
- det komplicerede i denne opgave er nok at værket skal være indlæst før man kan sende request afsted til recompass (fordi man har brug for værkets tags). Så man kan tilføje en componentWillReceiveProps metode, hvor man laver et tjek for om tags går fra at være ikke indlæst til indlæst.
- Når værk er indlæst kan man fyre en "RECOMMEND_REQUEST" action afsted

**Comment by KiraH** [comment]
testet OK
