### ISSUE TITLE
Redigering af bøger man har tilføjet til andres lister

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/content-first#256]
- [x] Den der har tilføjet en bog skal fjerne denne.
- [x] Den der har tilføjet en bog skal kunne redigere denne.
- [x] Ejeren af listen skal kunne fjerne alle bøger
- [x] Ejeren af en liste må ikke kunne redigere en andens beskrivelse
- [x] styling
- [x] profil-billede for element skal passe til ejeren af elementet og ikke ejeren af listen

**Comment by KiraH** [comment]
@vibjerg  hvad er det der skal retænkes?

**Comment by vibjerg** [comment]
Jeg har blot kopieret fra et andet issue. Tror @AndersFriisBrodsgaard kan svare på spørgsmålet.

**Comment by vibjerg** [comment]
Ved nærmere eftertanke, kan jeg måske godt svare. Indtil nu har elementerne i en liste været en del af listen, og sortering er sket ved at flytte rundt på rækkefølgen i et Array. Offentlige lister kræver at elementer i en liste er skilt ud i objekter for sig selv, og derfor skal man håndtere rækkefølgen ved hjælp af referencer til liste elementerne i stedet for selve liste element obekterne.
