### ISSUE TITLE
Performance ift bånd på forside skal forbedres

### ISSUE THREAD

**Issue by kfudbc** [DBCDK/content-first#258]
Efter der er kommet flere bånd til er forsiden blevet uacceptabelt sløv at indlæse.

**Comment by kfudbc** [comment]
Der er tilføjet lazy load på bånd, så bånd hentes ind ved vertikal scroll

**Comment by KiraH** [comment]
Der er stadig performanceproblemer på forsiden.

Vi skal have kigget nærmere på hvad problemet kan være.

Antallet af bånd?

Evt. brugen af recommender?

Herefter, hvad kan vi gøre ved det?

**Comment by KiraH** [comment]
Testet - done.
