### ISSUE TITLE
Rettelser i forhold til "Seneste lister fra brugerne" på forsiden

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#267]
- Man skal kunne se hvem der har oprettet listerne
- Der skal ikke vise likes
- Kommentar-antal skal slettes.
- "Seneste lister fra brugerne" overskrift skal ikke være klikbar.
- Hvis baggrundsbillede er tilføjet, bør dette vises i stedet for bogforsider.

**Comment by stanvins** [comment]
Likes og Kommentar fjernede via #264

**Comment by KiraH** [comment]
Det sidste punkt om at baggrundsbillede skal bruges i stedet for bogforsider er ikke implementeret.

**Comment by KiraH** [comment]
testet OK
