### ISSUE TITLE
På profilsiden skal der max vises 5 bøger pr liste 

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#269]
På siden http://content-first-s01.dbc.dk:8000/profile
- Der skal kun vises 5 værker samt antal yderligere værker i listen.
Det vil sige, at hvis der eksempelvis er 7 værker i listen skal der vises 5, som her 
![image](https://user-images.githubusercontent.com/28528078/37085124-8bb59f9c-21f4-11e8-933c-359a142310a5.png)
og derudover stå "+ 2 bøger mere" skal erstatte teksten "se hele listen".

**Comment by KiraH** [comment]
testet done
