### ISSUE TITLE
Typografien på liste-titel skal være anderledes på Profilsiden

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#270]
Listens titel vises ikke tydeligt nok. Se eksempel:
![image](https://user-images.githubusercontent.com/28528078/37085364-292d756a-21f5-11e8-8cb3-111322dbd62a.png)
Titlen: "Den bedste liste" skal være mere tydelig

**Comment by AndersFriisBrodsgaard** [comment]
Design:
![profil-dine-lister](https://user-images.githubusercontent.com/18284484/37092240-5c677384-220b-11e8-9f5b-3399a57c1c05.png)

**Comment by KiraH** [comment]
Done
