### ISSUE TITLE
De to default-lister "Har læst" og "Vil læse" skal tilføjes til profilsiden

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#271]
På siden: http://content-first-s01.dbc.dk:8000/profile, skal der tilføjes  "Har læst"-liste og "Vil læse"-lister. Listerne skal være der default
Listerne skal ikke kunne slettes
Listerne skal ikke kunne omdøbes.
Listerne skal ikke kunne gøres offentlige
Andre kan ikke tilføje på listerne.
Låst beskrivelse
Simpel liste visning
Standard billede til visningen

**Comment by KiraH** [comment]
Hvis ikke listerne er oprettet i forvejen findes de ikke på profiloversigten og de kommer heller ikke frem hvis man tilføjer bøger til dem.

**Comment by BettinaAndersen** [comment]
**Forslag til hurtig beskrivelse:**

Her kan du se listen over de bøger, som du har markeret som "Har læst". 
Du kan tilføje flere bøger til listen nederst på denne side.
Du kan redigere og fjerne bøger, men ikke slette selve listen.

Ovenstående genbruges for "Vil læse".

**Comment by KiraH** [comment]
testet done
