### ISSUE TITLE
Kommentarer bør kunne ses med det samme uden reload af listesiden.

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#276]
Accept: Når man har gemt en kommentar, ses denne med det samme, uden reload af siden.

Testes f.eks. ved at have samme liste åben i 2 forskellige vinduer. Herefter kan man skrive en kommentar til en liste/bog i det ene vindue og efter max 10 sekunder skulle samme kommentar gerne vise sig i det andet vindue.

**Comment by KiraH** [comment]
testet OK
