### ISSUE TITLE
Ved "Tilføj bøger til listen" skal der også stå at man kan søge på forfatter

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#278]
Lige nu står der kun at man kan søge titler, men man kan også søge på forfattere
![image](https://user-images.githubusercontent.com/28528078/37087195-e40550f2-21f9-11e8-9cfb-bc71b5816b16.png)

"Skriv titel eller forfatter"

**Comment by KiraH** [comment]
testet DONE
