### ISSUE TITLE
Udrulning af nye værker til content first hver nat

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#279]
Nye værker indtastet i Metakompasset bør rulles ud til Content First hver nat.

Der skal oprettes en pipeline til udrulning af data på de forskellige miljøer.

Hvis der er en fejl i et af jobbene stoppes udrulningen.

Ligeledes bør recommenderen opdateres med de nye værker og også køre hver nat. Dette kræver dog implementering af et sanity-tjek, som er ca 1½ dags arbejde for MikroSearch før det hele kan automaticeres.

**Comment by BettinaAndersen** [comment]
Afvente Mikrosearch

**Comment by BettinaAndersen** [comment]
Der skal stadig tænkes over en udrulnings-løsning, selv om vi venter på MikroSearch's implementering af kontroltjek.

**Comment by kfudbc** [comment]
MikroSearch har nu implementeret kontroltjek
