### ISSUE TITLE
Design: Opsætning af tekst/billede til systemlister

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#283]
"Har læst"- og "Vil læse"-listerne har specielle opsætninger, disse skal defineres:
- standardtekst til titel og beskrivelse
- standardbillede
Se i øvrigt #271 

Accept: Der eksisterer tekst og ikoner for de to lister.

**Comment by BettinaAndersen** [comment]
**Forslag til hurtig beskrivelse:**

Her kan du se listen over de bøger, som du har markeret som "Har læst". 
Du kan tilføje flere bøger til listen nederst på denne side.
Du kan redigere og fjerne bøger, men ikke slette selve listen.

Ovenstående genbruges for "Vil læse".
