### ISSUE TITLE
Design af banner til "opret profil"

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#286]
Banneret er af samme type som det banner, der tidligere har ligget på siden. Denne gang skal der være bedre tekst på banneret.
Se beskrivelse i #272

**Comment by BettinaAndersen** [comment]
Forslag til tekst: Opret en profil med dit bibliotekslogin og skab dine egne lister

**Comment by BettinaAndersen** [comment]
Sættes på backlog, da denne muligvis overhales af nyt design.

**Comment by BettinaAndersen** [comment]
Outdated
