### ISSUE TITLE
Værkdata skal indeholde info om, hvorvidt der findes et forsidebillede

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#287]
Når værkdata hentes ud i frontend, fx til visning af et værk i et bånd på forsiden, skal data indeholde info om der findes et forsidebillede og hvor det findes (metakompasset eller content-first DB).

Alternativt: Skal vi håndtere billeder anderledes, så de alle ligger samme sted som profilbilleder etc.. Så de nemt kan spille sammen den kode, der håndterer at levere billeder i vilkårlige størrelser?

**Comment by vibjerg** [comment]
Hvad er det for et problem der skal løses?

**Comment by BettinaAndersen** [comment]
Der skal tænkes en mere permanent løsning til håndtering af forsider. For nu skal cover-urlen sættes til null i metakompasset.

**Comment by kfudbc** [comment]
erstattes af https://github.com/DBCDK/content-first/issues/395

**Comment by BettinaAndersen** [comment]
Og lukkes derfor...
