### ISSUE TITLE
hvis man fjerner labels fra et bogmix kommer de ikke på igen

### ISSUE THREAD

**Issue by KiraH** [DBCDK/content-first#291]
Hvis man går ind på et bogmix og fjerner labels, skal labels komme på når man går tilbage til forsiden. Det gør de ikke ved hverken brug af browserens tilbagepil knap eller hvis man klikker på "Læsekompasset".

Ved reload af siden kommer labels på igen som de skal.

**Comment by BettinaAndersen** [comment]
Håndteres muligvis ved #310
