### ISSUE TITLE
Trin 0 : Forside: Grundlæggende opsætning

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#3]
Forsiden skal bygges op med:
-  Topbillede 
- "Bibliotekaren anbefaler"-bånd
- "En god bog"-bånd
- Opret profil (ikke klikbar grafik)
- Endnu et bånd? (Måske bare grafik?)

**Comment by kfudbc** [comment]
Fixed i den forstand at den grundlæggende opsætning er lavet - men ikke forbundet til backend. Båndene er lavet således at det er nemt at tilføje nye bånd. P.t. ligger disse bånd som en json-struktur i klient-delen - men på sigt kan de hentes ud af backend.

**Comment by KiraH** [comment]
Testet OK
