### ISSUE TITLE
I rediger profil snurrer evighedsspinner

### ISSUE THREAD

**Issue by KiraH** [DBCDK/content-first#301]
Under rediger profil står der "du er logget ind via" herefter er der en spinner der tilsyneladende aldrig bliver erstattet af noget andet.

**Comment by vibjerg** [comment]
Jeg kan ikke genskabe dette problem

**Comment by vibjerg** [comment]
/user endpoint på openplatform kan tage mere end 10 sekunder, og derved opstår der en timeout error. Det kan løses ved at sætte timeout tiden op. Der er oprettet et issue på openplatform klienten. 
https://github.com/solsort/openplatform/issues/1

**Comment by KiraH** [comment]
testet done
