### ISSUE TITLE
det skal være muligt at fjerne bøger fra de faste lister

### ISSUE THREAD

**Issue by KiraH** [DBCDK/content-first#302]
Det er ikke muligt at redigere listerne "Har læst" og "Vil læse". 

Dermed kan man heller ikke fjerne bøger fra listen igen.

Man skal hverken kunne om døbe eller slette listerne eller ændre beskrivelsen, men man skal vel kunne fjerne tilføjede bøger?

**Comment by BettinaAndersen** [comment]
JA! Det skal være muligt at fjerne bøger fra begge lister. Det skal blot ikke være muligt at slette eller omdøbe listerne.

**Comment by vibjerg** [comment]
Jeg tænker det måske kan give mening at genbruge funktionaliteten fra åbne lister, så man ikke har mulighed for at gå ind på redigeringssiden for systemlister, men man få mulighed for at slette vha. et lille kryds på listevisningssiden.

**Comment by KiraH** [comment]
testet DONE
