### ISSUE TITLE
fejl i bibliografiske data fra expandPids

### ISSUE THREAD

**Issue by cboesgaard** [DBCDK/content-first#31]
Anders og jeg undrede os over nogle bibliografiske data og nu faldt jeg over noget der helt sikkert ikke er kosher.

Jeg prøver at kigge på en Erlend Loe Doppler:

cat loe-pid.json 
["870970-basis:25775481"]

Ligger her:
https://gist.github.com/03b595abec97bd2ebc5c1925a86688ce

Kørsel:
./expandPids -i loe-pid.json -o loe-out.json -s http://cisterne-solr.dbc.dk:8983/solr/cisterne-corepo-searcher/select/ -m http://moreinfo.addi.dk/2.9/  -c http://content-service.corepo.cisterne.mcp1-proxy.dbc.dk/rest/objects/

Vi får:
https://gist.github.com/39c30a52d8af78a285969d7755f80c2f

Herunder:
**"titleFull" : "In Progress: SkyCity Orlando.",**
**Og ingen creator.**
Billedet er korrekt.

Bibliotek.dk finder det rigtige, derfor mistænker jeg bug her.
https://bibliotek.dk/da/search/work?search_block_form=870970-basis%3A25775481&select_material_type=bibdk_frontpage&op=S%C3%B8g&year_op=%2522year_eq%2522&year_value=&form_build_id=form-4zlMBC1SbqpbZ5n4EgGBfv8OGMTTsWtmFdUBFxdGgyk&form_token=4Rp_HcMOpxfz_7RDWMvgjGL0XZpEAPECTB_AK-W5Wy4&form_id=search_block_form&sort=rank_frequency&page_id=bibdk_frontpage#content

**Comment by cboesgaard** [comment]
Andet problem er at vi får "forkert" creator ud -- er der ikke en display title eller noget vi kan bruge?

Eksempel på problem:
{"pid":"870970-basis:22946188","unitId":"unit:861351","workId":"work:248599","bibliographicRecordId":"22946188","creator":"Sten Rasmus\
sen (f. 1936)","title":"Kældermennesket","titleFull":"Kældermennesket","type":"Bog","workType":"book","language":"Dansk","items":59,"l\
ibraries":52,"pages":191}

**Comment by fvsdbc** [comment]
Fixed
