### ISSUE TITLE
Redesign af filtersiden (Quickfix)

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#310]
1) Filtersiden skal være en generel filterside.  Dvs:
- [x] Man kan komme til den ved at klikke på en "Filter"-knap på forsiden eller (som nu) på et af båndene på forsiden. 
- [x] Hvis man klikker på eksempelvis "En god bog" skal man stadig ledes til filtersiden, hvor de prevalgte tags for "en god bog" er vist, men overskriften "Vis mig: En god bog" skal fjernes og selve siden bør ikke hedde "https://content-first.demo.dbc.dk/en-god-bog", men eks. "https://content-first.demo.dbc.dk/filter".
- [x] Hvis man klikker på "Filter"-knappen skal man havne på samme side, men uden forudvalgte tags.

- [x] 2) De eksisterende klikbare tags skal udskiftes med en ny kurateret liste med udgangspunkt i den nye taksonomi. Denne leveres af Læsekompasgruppen i uge 10.

- [x] 3) Der skal være et søgefelt på filtersiden, som har suggestfunktion (ikke fritekst-søgning). Suggestions er tags, som reelt benyttes i Metakompasset, dvs. kun tags, som er givet til bøger medtages. Der skal suggestes på begyndelsen af hvert ord i et tag, fx suggestes der på "Den 2. verdenskrig" ved indtastning af "ver", men ikke ved "krig".

- [x] 4) Det eksisterende design af filtersiden skal slankes, således at knapper og tekst gøres mindre - og muligvis udelades "tilføj"-knappen, hvis det bliver lettere at se resultatet af valgte tags. For design se issue: #311 

- [x] 5) Kun tags der er knyttet til en bog skal kunne vælges. Kræver nok at tags filtreres fra i taxonomy før CF bygges, da man ellers skal hente alle værker ud i grænsefladen for at lave filtreringen.

Accept: 
- Det skal være muligt at komme til filtersiden ved klik på knap på forsiden eller et bånd.
- Det skal være muligt at søge via suggestions på filtersiden
- Filtersiden skal anvende den nye taksonomi og følge nyt design

**Comment by AndersFriisBrodsgaard** [comment]
![filtrering_v2](https://user-images.githubusercontent.com/18284484/37572247-96af5560-2b08-11e8-865e-d27f0cf1ebf6.png)
![filtrering-v2-suggest](https://user-images.githubusercontent.com/18284484/37572248-96cafec8-2b08-11e8-8e5e-391679885fa8.png)
@kfu Har lavet design til filterside incl. suggest :point_up:

**Comment by KiraH** [comment]
testet done
