### ISSUE TITLE
DESIGN: Filtersiden på slankekur 

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#311]
- Det eksisterende design af filtersiden skal slankes, således at knapper og tekst gøres mindre - og muligvis udelades "tilføj"-knappen, hvis det bliver lettere at se resultatet af valgte tags.
- Der skal designes en knap på forsiden som leder til Filtersiden.

Accept: Der foreligger et design for begge.

**Comment by AndersFriisBrodsgaard** [comment]
Hvilke tags skal vises ved fold ud?
Stemninger
Tempo
Længde
Kvalitet
Handlingens tid - verbaliseret - 10 mest brugte
Handling - Springer i tid/sted, Handling på flere niveauer, Åben slutning, Lukket slutning
Evt. sproglig sværhedsgrad - almindeligt, lettilgængeligt  eller krævende sprog

**Comment by AndersFriisBrodsgaard** [comment]
![filtrering_v2](https://user-images.githubusercontent.com/18284484/37572280-130e3b26-2b09-11e8-8b62-36c433c1019a.png)
![filtrering-v2-suggest](https://user-images.githubusercontent.com/18284484/37572281-13255edc-2b09-11e8-8038-10018cdcb572.png)
