### ISSUE TITLE
Det skal være muligt at slette egne lister

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#325]
Via profil-siden skal det være muligt at slette egne lister (Dette gælder dog ikke systemlisterne; "har læst" og "vil læse").
Ved siden af Rediger-muligheden skal der være en Slet-mulighed.
![image](https://user-images.githubusercontent.com/28528078/37408819-2d60de76-279d-11e8-9ad2-66406d50833c.png)

Acceptkriterie: 
Ved klik på "Slet", skal hele brugerens liste slettes. 
Det skal ikke være muligt at slette systemlister
Det skal ikke være muligt at slette andres lister

**Comment by vibjerg** [comment]
Jeg synes vi skal overveje at lægge funktionen ind under rediger siden. Jeg tænker, at de fleste brugere godt kan finde ud af at gå ind under rediger, for at slette.

**Comment by KiraH** [comment]
testet done
