### ISSUE TITLE
Kan vi fjerne dubletter fra content-first?

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#339]
Der dukker dubletter op rundt omkring af enkelte bøger, som er blevet inddateret flere gange på forskellige PID'er. Har vi nogen mulighed for at fjerne dubletter? Fx vises "Eventyret om ringen" to gange ved siden af hinanden i båndet "Tolkiensque" på forsiden af content-first.

**Comment by kfudbc** [comment]
Skulle blive løst med rettelser i metakompasset: https://github.com/DBCDK/metakompasset/issues/127
