### ISSUE TITLE
Man kan ikke logge ud af content-first, Hvis man allerede er logget ud af adgangsplatformen

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/content-first#342]
Hvis man logger ind på bibliotek.dk go content-first med adgangsplatformen, og derefter logger ud af bibliotek.dk, så kan man ikke logge ud af content-first, men ender på en fejlside i adgangsplatformen. 

Acceptkriterie: Hvis man logger ud af content first, logger man ikke ud af Adgangsplatformen.

**Comment by BettinaAndersen** [comment]
Der skal findes en generel løsning til håndtering af skift mellem forskellige tjenester samt logud. Dette tages op i "governance-forum" med DDB torsdag den 12. april.

**Comment by KiraH** [comment]
lukker
