### ISSUE TITLE
Huskeliste: Fejl ved "tilføj til liste" uden login

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#346]
Hvis man ikke er logget ind, og forsøger at tilføje en bog - eller alle bøger - til en liste på siden http://content-first-s01.dbc.dk:8000/huskeliste, så vises en blank side.

Accept: En anonym bruger skal promptes til at logge ind, hvis han forsøger at tilføje bøger til en liste fre huskeliste-siden.

**Comment by KiraH** [comment]
testet OK
