### ISSUE TITLE
Nogle lister mangler elementerne på listevisningssiden

### ISSUE THREAD

**Issue by kfudbc** [DBCDK/content-first#348]
Muligvis noget at gøre med nye vs gamle lister problematik

https://content-first.demo.dbc.dk/lister/ab5b97f8-79ca-4543-bc68-a0ba7fef7a2d

**Comment by vibjerg** [comment]
For den enkelte liste kan det løses ved at man går ind og gemmer listen på ny. Og ellers foreslår jeg at vi bare sletter alle lister.

**Comment by BettinaAndersen** [comment]
Tænker denne kan lukkes?

**Comment by vibjerg** [comment]
Ja, Den skal bare lukkes.
