### ISSUE TITLE
Filterside: Vis kun bøger resultatet, der har over 0 i vægt

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#358]
En søgning på "Hajer" giver en masse resultater, der har value=0, men der er kun én bog, der har tagget hajer på sig. Det er forvirrende. Derfor kan det give mening, at fjerne alle resultater, der har en score på 0, så vi er sikre på, at hvert resultat i hvert fald matcher ét tag fra søgningen.

**Comment by kfudbc** [comment]
Løsningsforslag:
- FilterPage.container.js benytter en getRecommendations-funktion (selector), som returnerer de forslag som matcher de valgte tags. getRecommendations kan modificeres, så den tager en threshold-værdi som parameter.
- value-informationen gemmes på nuværende tidspunkt ikke i redux statet. Så src/client/redux/recommend.js skal bringes til at gemme denne information også

**Comment by KiraH** [comment]
testet OK
