### ISSUE TITLE
Alle tags på værkside skal være aktive

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#369]
- [x] På værksiden skal alle tags være aktive og linke til filtersiden
- [x] På værksiden skal tags vises i lille størrelse / lys grå, svarende til hvordan de ser ud i filterboksen. 
- [x] Første bogstav i et tag skal være stort, men ikke første bogstav i alle ord i tagget. 
- [x] Ensart tag class' på sitet

Kan evt. laves som komponent eller som CSS-klasse

**Comment by KiraH** [comment]
testet Done
