### ISSUE TITLE
More attributes in database

### ISSUE THREAD

**Issue by jpsecher** [DBCDK/content-first#37]
Content First needs to support the following book attributes:

subject
taxonomyDescription
bibliographicDescription
dateFirstEdition (year == int)
genre
literaryForm

**Comment by jpsecher** [comment]
{
	  "pid": "870970-basis:53188931",
	  "unitId": "unit:22125672",
	  "workId": "work:20137979",
	  "bibliographicRecordId": "53188931",
	  "subject": "billedværker, humor, fotografier",
	  "genre": "humor",
	  "description": "Fotografier af havelåger sat sammen med korte tekster, der fantaserer over, hvem der mon bor inde bag lågerne",
	  "dateFirstEdition": "2017",
	  "literaryForm": "digte, fiktion",
	  "creator": "Jens Blendstrup",
	  "title": "Havelågebogen",
	  "titleFull": "Havelågebogen : trælåger, gitterlåger, fyldningslåger, jern- og smedejernslåger",
	  "type": "Bog",
	  "workType": "book",
	  "language": "Dansk",
	  "items": 101,
	  "libraries": 45,
	  "pages": 119,
	  "image_detail_117": "https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=53188931&attachment_type=forside_117&bibliotek=870970&source_id=870970&key=6dfb4a4381e1e2937c96",
	  "image_detail_207": "https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=53188931&attachment_type=forside_207&bibliotek=870970&source_id=870970&key=b984e9e997fe47674175",
	  "image_detail_42": "https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=53188931&attachment_type=forside_42&bibliotek=870970&source_id=870970&key=ff913149de26bd6fb49f",
	  "image_detail_500": "https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=53188931&attachment_type=forside_500&bibliotek=870970&source_id=870970&key=a9a1733a5f0a6a5f9de4",
	  "image_thumbnail": "https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=53188931&attachment_type=forside_lille&bibliotek=870970&source_id=870970&key=9e13493170a237876282",
	  "image_detail": "https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=53188931&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=1826257d1e6b463f847e",
	  "loans": "14"
	}

**Comment by BettinaAndersen** [comment]
Testet ok i drift
