### ISSUE TITLE
Opdatering af taxonomi

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#382]
Der er kommet en række opdateringer til taxonomien fra Metadata. Se vedhæftede dokumenter. 

Primært er der tale om nye/ændrede/slettede tags, men der er også en mindre strukturel ændring i Miljø, hvor flere underkategorier skal lægges sammen. 

[Fortælleteknik.revideret20.03.18.docx](https://github.com/DBCDK/content-first/files/1879603/Fortaelleteknik.revideret20.03.18.docx)
[Handling.revideret20.03.18.docx](https://github.com/DBCDK/content-first/files/1879604/Handling.revideret20.03.18.docx)
[Ramme.revideret20.03.18.docx](https://github.com/DBCDK/content-first/files/1879605/Ramme.revideret20.03.18.docx)
[Stemning.revideret20.03.18.docx](https://github.com/DBCDK/content-first/files/1879606/Stemning.revideret20.03.18.docx)

**Comment by KiraH** [comment]
testet OK
