### ISSUE TITLE
Link til litteraturside-anmeldelser

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#389]
Der skal være link til litteraturside-anmeldelser fra en værkside. Eksempelvis: https://content-first.demo.dbc.dk/v%C3%A6rk/870970-basis:28894287

**Comment by BettinaAndersen** [comment]
Eksempel: Mit navn er Lucy Barton
http://content-first-s01.dbc.dk:8000/v%C3%A6rk/870970-basis:53089100
https://litteratursiden.dk/node/81907

Der findes link fra bibliotek.dk:
https://bibliotek.dk/da/search/work?search_block_form=Mit+navn+er+Lucy+Barton&select_material_type=bibdk_frontpage&op=S%C3%B8g&year_op=%2522year_eq%2522&year_value=&form_build_id=form-quMYH2t-dBAI72PFQjEAPaKWv1ALcMGTfeQRpWCr4gk&form_id=search_block_form&sort=rank_frequency&page_id=bibdk_frontpage#content

**Comment by rasmuserik** [comment]
Umiddelbart ser det ikke ud til at disse er direkte tilgængelige i den åbne platform. (Til gengæld er der info om anmeldelser, inkl info om antal stjerne).

**Comment by KiraH** [comment]
testet done
