### ISSUE TITLE
Returside efter login ifm. lån

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#393]
Når man gerne vil låne bøger, bliver man bedt om at logge ind. Det går fint. Men efter login bliver man sendt tilbage til forsiden med en pop-op, der forklarer, at bøger er overført til en huskeliste. I stedet skal man gå til næste skridt i låne-flow.

Løsning: Pop-up med overførsel af bøger til huskeliste skal deaktiveres (generelt) - Måske nyt issue.  Acceptkriterie: brugeren skal sendes videre i låneflowet.

**Comment by KiraH** [comment]
Pop-up generelt deaktiveret og man sendes videre i låneflow.

Testet OK.
