### ISSUE TITLE
Hente forsider gennem openplatform

### ISSUE THREAD

**Issue by kfudbc** [DBCDK/content-first#395]
Forsider skal hentes direkte fra openplatform. Openplatform kan kaldes på samme måde som med bestilfunktionalitet - altså direkte fra klienten med token.

På denne måde slipper vi for noget kompleksitet i forhold til at gemme forsider i metakompas/content-first, og vi gør brug af eksisterende infrastruktur

**Comment by rasmuserik** [comment]
... ser ud til at vi kun har openplatformtoken når brugeren er logget ind, - så dette kræver nok også en ændring i backend'en.

**Comment by rasmuserik** [comment]
Kaldende til openplatform/moreInfo giver performance-problemer, hvilket er oprettet som separat issue #442
