### ISSUE TITLE
Facebook deling af værkvisningsside 

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#397]
Det skal være muligt at dele et værk via Facebook.
Deling skal ske fra sider, som denne: https://content-first.demo.dbc.dk/v%C3%A6rk/870970-basis:53089100
Placering af Facebook-delings-ikon aftales med Anders,

Ved deling skal Forsidebillede, titel, forfatter og kort beskrivelse deles:
Eks:
- Mit navn er Lucy Barton
- Elizabeth Strout
- Gribende og varm beretning. Psykologisk, dybsindig og melankolsk

Hvis "plads" kan indholdsnote-tekst også deles.
Eks: Om en fattigdomsramt barndom i USA's midtvest og det til tider, svære kærlighedsforhold mor og datter i mellem.

Acceptkriteie: Der skal være et facebook-ikon på værkvisnings-siden, som deler et værks forside, titel, forfatter og kort test.

**Comment by KiraH** [comment]
OK
