### ISSUE TITLE
https://content-first.demo.dbc.dk/ virker ikke i IE

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#404]
Der kommer bare en blank side.
Testet i:
![image](https://user-images.githubusercontent.com/28528078/38679965-684171c0-3e65-11e8-80d4-2d39c9966bf7.png)

Acceptkriterie; https://content-first.demo.dbc.dk/  skal virke i IE.

**Comment by KiraH** [comment]
Virker stadig ikke I min IE 11, der kommer stadig kun en blank side.

**Comment by KiraH** [comment]
Virker stadig ikke i min IE 11. Der kommer kun en blank side.

**Comment by kfudbc** [comment]
Virker på windows testmaskine i IE11

**Comment by KiraH** [comment]
Testet OK
