### ISSUE TITLE
Personaliseret bånd på forsiden

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#405]
Når vi begynder at opsamle brugeradfærd, se #76 , så skal der oprettes et bånd på forsiden med overskriften "Bedste forslag til >profilnavn<" .  Indholdet skal være anbefalinger baseret på de opsamlede pid'er for brugeren.

Gælder kun for en indlogget bruger.

Spørgsmål: Hvad viser vi indtil vi har opsamlet data for brugeren? 
SV: Bånd skal først vises når vi har data.
Spørgsmål: Hvilke typer events skal vi medtage, som baggrund for de givne anbefalinger?
SV: Til det første bånd tænkes alle events. Hvordan data ellers skal udvælges skal diskuteres med Læsekompasset.
Spørgsmål: Hvor mange events (eller inden for hvilken tidsramme) skal vi anvende?

Acceptkriterie: For en indlogget bruger skal der vises et bånd på forsiden med anbefalinger baseret på brugerens tidligere interaktion med andre bøger.

----

Et par hurtige noter om hvordan det kan implementeres:

- Vi skal opdatere anbefalingerne til det personaliserede bånd når forsiden vises.
    - Dette kan gøres med middleware som kun kaldes når vi er på forsiden, og der er ændringer i personaliseringsdata siden sidst.
    - Det skal sikres at vi har indlæst metadata for de materialer som anbefalingerne baserer sig på.
    - Forespørgsl mod recommender i stil med hvorledes den kaldes andetsteds.
- Det personaliserede bånd skal vises
    - Kan de eksisterende komponenter for bånd genbruges?
    - Ellers skal komponent for personaliseret bånd implementeres.

**Comment by KiraH** [comment]
testet done
