### ISSUE TITLE
Analyse af hvorvidt Community-servicen (Elvis) kan bruges til profilhåndtering.

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#41]
Kræver input fra læsekompasset omkring endelig Profil-funktionalitet. I første omgang bør dog ses på muligheden for at bruge community-servicen til opbevaring af profil-stam-data og lister.

**Comment by BettinaAndersen** [comment]
Som det ser ud lige nu vil en profil består at noget stam-info (minimum køn og alder) og et antal "smagsprofiler". Hver "smagsprofil" er opbygget af lister betsående af forfattere, stemninger og lokationer. Derudover er der en nysgerrigheds- parameter og evt. en arketype. (En arketype er blot et prævalgt-antal af forfattere, stemninger og lokationer). Derudover er der i content-first en række filtre, som kan vælges under "passer-med-min-smag". Disse bør også på sigt kunne tilknyttes profilen.

**Comment by jpsecher** [comment]
i øjeblikket er der bl.a. disse data i content-first:

name: 'Jens Hansen'
gender: 'm'
birth_year: 1921
authors: ['Georg Brandes', 'Hans Kirk']
atmosphere: ['Tænksomt', 'Adstadigt']

**Comment by KiraH** [comment]
Det kan den godt
