### ISSUE TITLE
Bogreol som liste template

### ISSUE THREAD

**Issue by mtni** [DBCDK/content-first#412]
"De kendtes bogreol" skal laves som et nyt template valg når man vil oprette/redigere en liste. 

Bogreol templaten skal være åben for alle, men man kan have nogen udvidet redigeringsmuligheder, hvis man har redaktør adgang, f.eks. ændring af navn, profilbillede mv. Så man kan oprette bogreoler på baggrund af andre end en selv (andet issue)

Når bogreol templaten vælges, bruges alle de eksisterende felter (beskrivelse til bogreol-beskrivelse, bog-kommentare til bog-kommentarer, osv.) Men som noget unikt til denne template, skal der laves en løsning til håndtering af bøgernes positioner på bogreolen (de pulserende prikker). 

### Løsningsforlag: 
- At udvide billedeupload feltet til samme størrelse som resten af input felterne. 
- Herefter indsættes automatisk nogen prikker (svarende til antallet af bøger på listen) tilfældigt rundt på billedet. 
- Brugeren kan herefter drag-and-drop prikkerne så de stemmer overens med bøgerne på deres bogreol. 

Husk at der også skal tages højde for tablets/touch.

- [x] Upload og udvidelse af bogreol billede (Så det flugter med de øvrige felter)
- [x] Automatisk indsættelse af prikker (baseret på bøger i listen)
- [x] Drag-and-drop løsning af prikkerne
- [x] Opdater prikkernes position når der dragges.
- [x] Husk prikkernes position når der gemmes.
- [x] Bogreolen skal være synlig mellem de andre lister på forsiden (Seneste lister fra brugerne)

_______________________________________________________________________________

#### Success kriterie:
Der kan oprettes, redigeres og vises brugerskabte bogreoler. Den nye listetype skal også være tilgængelig fra forsiden under seneste oprettede lister.

**Comment by KiraH** [comment]
testet done
