### ISSUE TITLE
Gammel liste som bogreol

### ISSUE THREAD

**Issue by mtni** [DBCDK/content-first#418]
Hvis en allerede oprettede liste (simpel el. visuel), ændres til en bogreol template. Vil bøgerne som allerede er i listen ikke have en position key på sig, før de bliver rykket.

Dette resulterer i at hver gang en bog flyttes vil alle bøgerne som ikke har en position key, blive flyttet random rundt. 

Løsning: At tjekke om alle bbøger har en key, og hvis ikke, skal de have en fra start, så snart liste templatet bliver triggeret.

TEST: Ændre en gammel liste til en bogreol og ryk på "bog-dotterne" så snart en "bog-dot" slippes, må ingen af de andre "dotter" flytte på sig.

**Comment by KiraH** [comment]
testet done
