### ISSUE TITLE
GDPR - sletning af data (backend)

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#430]
Når brugeren sletter indhold, så som lister eller kommentarer, skal de slettes helt.

Det skal være muligt for brugeren at vælge at slette sin profil.
Alle data - inklusiv oprettede lister og kommentarer skal herefter slettes.

----
Dette issue omhandler backen-delen, har også oprettet issue #449  om frontend, der afventer at backenden har API til sletning.

- [x] overblik over hvilke brugerdata der er / bruges (gennemgå endpoints for brugerdata)
- [x] håndtering af userId vs openplatformId: eksempelvis openplatformToken+openplatformId i DB
    - [x] migration add `openplatform_id` to cookie-table
    - [x] server/external-hejmdal.js insert `openplatform_id` in cookie-table
    - [x] make sure cookies in test has `openplatform_id`
    - [x] update server/objectStore.js to do lookups in cookie-table for openplatformid
- [x] `v1/image`: 
    - [x] tilføj optional owner, så brugerens billeder kan slettes
    - [x] fix tests (fails, due to that the user in the test does not have a profile with openplatformId).
- [x] `v1/object`: 
    - [x] brug content-first databasen, hvor data lettere kan slettes
    - [x] coverage acceptance test
- [x] user data
    - [x] refaktorer: udtræk API for objekt-endpoint funktionalitet i backend
    - [x] gem openplatform token i cookie-table
    - [x] enklere internt api til at hente/gemme brugerdata, som også migrerer data samtidigt.
    - [x] omskriv external-v1-(user|shortlist|login|logout) til at bruge internt api
    - [x] ret external-hejmdal og få login til at virke igen til at bruge det nye api
    - [x] brug openplatformid som id hvis der ikke er noget communityservice-id, (og lad -1 være manglende communityservice-id, indtil vi har fjernet community-servicen).
    - [x] tilføj kode for brugeroprettelse uden community-service og ret external-hejmdal til at bruge denne
- [x] omskriv tests af login/logout/shortlist/user fra integration til acceptance (så de ikke afhænger af community servicen).
    - [x] object
    - [x] user
    - [x] shortlist
    - [x] login
    - [x] logout
- [x] øvrig kode
    - [x] ret external-meta-list.js fra at bruge community service getObjectById til at bruge tilsvarende i objectStore.
- [x] oprydning:
    - [x] opryd i kode genbrugt fra gamle tests
    - [x] slet outdatede tests i stedet for blot at skippe dem.
    - [x] deprecate endpoints der ikke ser ud til at bruges: `v1/lists`, `v1/public-lists`  `v1/profiles`.
    - [x] fjern communityservicen
- [x] endpoint til udlevering / sletning, af data for brugeren.

**Comment by rasmuserik** [comment]
Efter at have dykket ned i koden, er konklusionen at det nok er lettest at implementere dette, ved at flytte objekt-endpointet over, så det ligger direkte ovenpå postgres-databasen (da community-servicen på nuværende ikke understøtter sletning, samt gemmer en log, som vi måske ikke har hjemmel for at gemme). Shortlist og user kan herefter bruge objekt-endpointet. Dette gør det også letter at genbruge koden for objekt-endpointet i andre sammenhænge, - eksempelvis hvis lignende funktionalitet skal implementeres i DÅP.

**Comment by rasmuserik** [comment]
Så er pull-requesten merget, hvilket gør at data slettes rigtigt.

(der ligger stadig nogle gamle data i community-servicen, der ikke tilgås mere, - disse slettes når/ved at community-service fjernes)

**Comment by KiraH** [comment]
lukker denne
