### ISSUE TITLE
datapipeline "2.0": fra metakompas til content-first  

### ISSUE THREAD

**Issue by cboesgaard** [DBCDK/content-first#44]
Vi har gennemgået det ved tavlen.

Der skal ryddes op i de nuværende scripts, navne skal synkroniseres og det skal i jenkins.

ACCEPT: skal køre som IS-job der bygger json-artifakter der fx kan bruges fra content-first byg.

**Comment by cboesgaard** [comment]
Vi skal have den del der laver rapporter til at være helt uafhængig af resten. Bl.a. fordi vi talte os frem til at have et job der fra data bygger alt der skal til for at deploye en content first (og kun kommer til at lave ny data sammen med deploy).

**Comment by KiraH** [comment]
Der er sat job op til reports der er sat til at køre hver nat.

**Comment by cboesgaard** [comment]
Ovre i metakompasset har jeg i dag skrevet kode der hiver data fra nye endpoints og laver:
 * pidinfo.json: exportWorks.json with added "taxonomy_description"
 * similar-pids.json: similar pids (100 most similar)
Herunder rettet en fejl i det der laver descriptions. Der mangler stadig oprydning i den kode der laver "profiler/minsmag".

**Comment by cboesgaard** [comment]
Udgangspunktet for profiler (list af pid'er) er nu flyttet ud i seperat fil (base-profiles.json)
