### ISSUE TITLE
Det skal være muligt at slette sin profil - Frontend

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#446]
Der skal være en funktion under Profil, hvor brugeren kan slette sin profil. Der bør være en pop-up, som spørger om brugeren er sikker.

Accept-kriterie. Det skal være muligt at slette sin profil, hvorved alle underliggende data, så som lister og kommentarer også slettes. Hvis brugeren efterfølgende trykker login, skal et nyt "opret profil"-flow starte. (Profilen skal ikke genoplives).

Relateret til backend-issue: #431

**Comment by mtni** [comment]
Afventer issue #431 #430

**Comment by mtni** [comment]
@rasmuserik Har du noget dokumentation for sletning af profil som jeg kan kigge på? Eller er det nemmere at vi lige stikker hovederne sammen?

**Comment by KiraH** [comment]
testet OK
