### ISSUE TITLE
Bliver bedt om at oprette profil, når jeg logger ind med et andet bibliotek

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#448]
Jeg har en profil oprettet p baggrund af mit Herlev-login. Når jeg logger ind med mit Frederiksberg-login bliver jeg bedt om at oprette en profil, selv om det er mit CPR jeg bruger som identifikation begge steder. 

Desuden kan Content-first ikke få kontakt til servicen, der skal fortælle hvor jeg er logget ind fra. Se dump
![screenshot 2018-05-25 11 49 42](https://user-images.githubusercontent.com/18284484/40538539-4cd30132-6012-11e8-8aaa-16085f3d6e72.png)

**Comment by vibjerg** [comment]
Anden del af issuet er løst ved at openplatform har nedgraderet til at benytte openagency 2.24 i stedet for 2.34.
