### ISSUE TITLE
Nyt design: Topbar

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#452]

**Comment by AndersFriisBrodsgaard** [comment]
Design til desktop her
![screenshot 2018-06-11 14 02 41](https://user-images.githubusercontent.com/18284484/41230450-2d9dbcf0-6d80-11e8-9866-ff3fd027436d.png)

Se wireframes for desktop og mobil her:
https://pblcte.axshare.com/#g=1&p=topmenu_august_2018

Acceptkriterier til denne første implementering af designet:
Søge-ikonet skal linke til søgesiden
Menupunktet "Lister" skal linke til profilsiden (hvor man kan se sine lister)
Linket "Log ud" skal bevares til højre for profilbilledet

**Comment by BettinaAndersen** [comment]
Logo skal være nuværende med "Læsekompasset"-tekst.

**Comment by KiraH** [comment]
Topbar ser fin ud, jeg opretter et issue på at der skal kigges på søgefeltet og lukker denne.
