### ISSUE TITLE
Nyt design: Brugernes lister (forsidevisning)

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#453]
Design:
![screenshot 2018-06-11 14 47 24](https://user-images.githubusercontent.com/18284484/41232460-b9978adc-6d86-11e8-9e21-2996431ad216.png)

Se design nederst på siden her:
http://diblio2.webflow.io

Acceptkriterier for denne version af designimplementationen:

- "Mere"-ikonet (de tre små prikker) skal ikke implementeres
- Der skal ikke stå titel under brugernavn (fx "Bibliotekar")
- Der skal ikke være noget "Like"-ikon
- Antallet af kommentarer er et samlet antal for hele listen, incl. de kommentarer, der ligger på de enkelte værker i listen (Gemmes til senere, hvis ikke vi har det)

**Comment by KiraH** [comment]
testet done
