### ISSUE TITLE
Nyt design: Værksiden

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#461]
Værksiden skal groomes og designet gøres klar til næste sprint.
Bysted har leveret et design, men funktionalitet som vi endnu ikke har, som forfattervisning og priser, skal pilles ud.
Det tages op på næste grooming møde om vi kan/bør vise tilgængelige medietyper (ikke som søgemulighed).
Der skal tages stilling til hvordan værksiden skal se ud i mobil-layout.

**Comment by AndersFriisBrodsgaard** [comment]
Desktop version
![desktop-vaerkside](https://user-images.githubusercontent.com/18284484/41697885-66f0540c-751b-11e8-9659-01dd2eaecd7a.png)

**Comment by AndersFriisBrodsgaard** [comment]
Mobil version: Elementerne vises i følgende rækkefølge:
Forside (incl Facebook-knap)
Venstrespalte (Titel, forfatter etc.). 
Højrespalte (Anmeldelser)
Bånd med "Minder om..."
