### ISSUE TITLE
Nyt design: Tilføj til liste og husk knap for en indlogget bruger

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#462]
Tilføj til liste-knap, desktop:
![screenshot 2018-07-10 13 06 15](https://user-images.githubusercontent.com/18284484/42507266-d18c5bc0-8444-11e8-940b-d21187b7df8a.png)

Tilføj til liste-knap, mobil:
![screenshot 2018-07-10 13 27 43](https://user-images.githubusercontent.com/18284484/42507328-08594c80-8445-11e8-8f68-5d52071cee3a.png)

Husk, desktop + mobil
![screenshot 2018-06-13 14 29 31](https://user-images.githubusercontent.com/18284484/41351318-46ab3c9e-6f16-11e8-84fa-b14aa2b9512d.png)

Husk-knappen er nu en selvstændig knap med én funktion - at tilføje/fjerne en bog fra huskelisten. 
På et bånd vises den kun med ikon (bogmærke), mens den i værkvisning ses som en knap med både ikon og teksten "Husk".

Husk-knap her: http://diblio2.webflow.io
Tilføj til liste-knap og stor husk-knap her: http://diblio2-book.webflow.io

Tilføj til liste er en selvstændig knap med dropdown-lignende egenskaber. Teksten på knappen ændrer sig alt efter om bogen ligger på en eller flere af brugerens lister eller om brugeren har læst den, efter følgende prioritet:
1. Systemlisten "Har læst"
2. Den liste, som bogen senest er blevet tilføjet til (hvis det ikke kan lade sig gøre, så den nyeste liste, hvorpå bogen ligger) 
3. Systemlisten "Vil læse"

Når der klikkes på "Tilføj til liste" vises følgende elementer i en dropdown
1. Op til 3 af brugeren egne lister, som 
- bogen findes på eller
- senest er anvendt af brugeren (alternativt nyeste lister, brugeren har oprettet)
2. "Har læst" og "Vil læse" systemlisterne
3. "Tilføj til anden liste", hvis brugeren har andre lister end de allerede viste
4. "Tilføj til ny liste"
De lister, som bogen allerede befinder sig på, er markeret med en farvet cirkel.
Wireframes her: https://pblcte.axshare.com/#g=1&p=l_g_p__liste

Der skal også tænkes i mobil-layout.

**Comment by AndersFriisBrodsgaard** [comment]
@mtni jeg har lavet specs fra Sketch her:
https://www.dropbox.com/sh/xi8ezbmnlh4ie57/AADan9z4s3xjWZWduYAqKayja?dl=0
