### ISSUE TITLE
Nyt design: Styling af huskelisten

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#463]
Der skal også tænkes i mobil-layout.

**Comment by AndersFriisBrodsgaard** [comment]
Desktop
![huskeliste desktop](https://user-images.githubusercontent.com/18284484/41702795-a2313656-7531-11e8-9eeb-f28c909867b3.png)

**Comment by AndersFriisBrodsgaard** [comment]
Mobil - huskelisten linker direkte til profilsiden (som pt. er en listeoversigtsside)
