### ISSUE TITLE
Design: reaktion ved klik på følg liste når brugeren ikke er logget ind

### ISSUE THREAD

**Issue by KiraH** [DBCDK/content-first#475]
Når brugeren klikker på "følg" liste uden at være logget ind kommer der ingen reaktion.

Der skal gives en besked til brugeren om at man skal logge ind for at kunne følge en liste.

Det skal overvejes hvordan det skal se ud og hvad der skal stå.

**Comment by AndersFriisBrodsgaard** [comment]
Design på generelt modal til at prompte brugeren til at logge ind, se nedenfor.

Tekst til modal: 
"Følg liste"
"Du skal logge ind for at følge en liste"

Mobil
![mobile-log in modal](https://user-images.githubusercontent.com/18284484/42569382-a13fa0fe-8510-11e8-9c22-5faeffd3fe4e.png)


Desktop
![desktop-log ind modal](https://user-images.githubusercontent.com/18284484/42569388-a7f55c54-8510-11e8-83b3-7f7a4e332f00.png)
