### ISSUE TITLE
Søgning og filtrering

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#478]
Mobil:
Søge-ikonet i topmenuen er et link til søgesiden. På søgesiden vises et tomt søgefelt i topmenuen (eller lige under). På siden vises øverst en række tiles med filtre og derunder et par bokse med søgeforslag - nogle redaktionelt udvalgte, andre baseret på brugerens tidligere søgninger / præferencer.
Når brugeren skriver i tekstfeltet, vises der suggestions baseret på det indtastede.
Så snart brugeren har valgt et tag, skubbes forslagsboksene ned på siden, under resultatet af søgningen.
Når brugeren vælger en suggestion fra dropdown vises det valgte tag i søgefeltet øverst og resultatet af søgningen vises på siden, under filtrene. 
Til højre for søgefeltet vises en "Søg"-knap, som ved klik aktiverer søgefeltet til tekstinput

Når en kategori er åbnet/aktiveret, skal det markeres med baggrundsfarve
Når et tag fra en kategori er valgt, skal man kunne se det i kategorien
Når et tag fra en kategori er valgt, skal det så vises i kategorien?

Basis for en række issues:
- filterboks incl markering af valg (mobil og desktop)
- udfoldning af valgt filterboks (mobil)
- udfoldning af valgt filterboks (desktop)
- søgefelt funktionalitet (mobil)
- søgefelt funktionalitet (desktop)
- suggestions (mobil og desktop)

**Comment by AndersFriisBrodsgaard** [comment]
Design og specs findes her:
https://www.dropbox.com/sh/oght1jjttyfi85s/AABj3kPXgsQCvAOsZ3GRU3T2a?dl=0

**Comment by AndersFriisBrodsgaard** [comment]
@mtni Vil du skrive issues på de enkelte dele af denne story?

**Comment by AndersFriisBrodsgaard** [comment]
Så kan jeg nemlig lukke den...

**Comment by mtni** [comment]
Jeps, implementerings issue givet i #546 

Det er lavet som et stort samlet issue, men med steps i form af en checkbox oversigt.
