### ISSUE TITLE
Implementering af nyt design: DE KENDTES BOGREOL

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#494]
Design er givet i #493

**Comment by stanvins** [comment]
[] Reverse components in top row

**Comment by stanvins** [comment]
- [ ] Reverse BookcaseItems

**Comment by KiraH** [comment]
"forsiden" på bogreolen er implementeret med hardkodet tekst. Resterende opgaver er der oprettet nyt issue på. Jeg lukker dette.
