### ISSUE TITLE
Error:  dispatch is not a function

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/content-first#503]
Jeg får forøjeblikket en fejl:

```
Unhandled Rejection (TypeError): dispatch is not a function
(anonymous function)
src/client/utils/requester.js:53
  50 |   return books;
  51 | })
  52 | .catch(error => {
> 53 |   dispatch({
  54 |     type: 'LOG_ERROR',
  55 |     actionType: BOOKS_RESPONSE,
  56 |     pids,
View compiled
```

Når der sker en fejl med indlæsningen af bøger.

**Comment by rasmuserik** [comment]
Fejlen kommer eksempelvis når databasen er nede.

Ser ud til at den skyldes at partialUpdateRequest tager en `requestFunction`, eksempelvis fetchBooks eller fetchReviews, - desværre tager fetchBooks en dispatch-funktion med som anden parameter, og fetchReviews forventer en store som anden parameter.

**Comment by mtni** [comment]
Jeg er ret sikker på jeg vil løse den med pull request #513 

Men jeg fik ikke nogen fejl hverken før eller nu, så jeg har ikke rigtig kunne teste det.

**Comment by BettinaAndersen** [comment]
Er det noget der kan testes @rasmuserik ??
