### ISSUE TITLE
Design knækket på listevisningssiden. 

### ISSUE THREAD

**Issue by mtni** [DBCDK/content-first#510]
Hvis der er tilføjet bøger til en liste som vises på listevisningssiden, knækker noget alignment i designet ved preview af de bøger som er i listen. 

https://content-first.demo.dbc.dk/profile

Acceptkriterie: 
Preview af bøgerne i listen skal vises på linje som før.

**Comment by mtni** [comment]
![screenshot from 2018-06-27 12-56-53](https://user-images.githubusercontent.com/36037828/41979727-0f3d3fa4-7a25-11e8-89f0-1a721b35dd38.png)

**Comment by KiraH** [comment]
testet OK
