### ISSUE TITLE
Find alternativ til session storage, som virker på alle browsere

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#526]
Når man logger ind via adgangsplatformen på fx Safari/OSX får man en spinner på siden, da session storage fra før brugeren blev sendt til adgangsplatformen er blevet slettet (en feature). Det virker fint i fx Chrome. 

Det betyder:
- at brugeren ikke kan sendes tilbage til den side, han loggede ind fra
- at huskelisten tømmes, hvis brugeren går over på et andet site i samme tab 

Tidligere har vi brugt local storage, men det gemte data på tværs af sessioner, hvor browseren havde været lukket ned. Vi skal altså finde et alternativ, som gemmer mere konsistent, men samtidig huske at få fjernet brugerens login-state ved lukning af browser.

**Aftalte til planning bare at implentere Quickfix: Hvis replay ikke virker skal man komme til forsiden.**

**Comment by KiraH** [comment]
testet OK
