### ISSUE TITLE
Ved klik på "mere som denne" skal siden scrolles ned om nødvendigt

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#528]
Ved klik på "mere som denne" skal siden scrolles ned, for at sikre at det nye bånd bliver synligt. Dette er for at undgå at brugen ikke misser det nye bånd, hvis dette dukker op uden for skærmens synsfelt.

![image](https://user-images.githubusercontent.com/28528078/42309653-7dce08c6-8039-11e8-818b-c4ed1b65595b.png)

**Comment by KiraH** [comment]
testet OK
