### ISSUE TITLE
Listevisning fra topbar for en inlogget bruger

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#530]
Ved klik på listeikonnet i topbaren skal der vises en listeoversigt med egne lister samt lister man følger, sorteret efter:
- oprettelsesdato for egne lister 
- dato, man begyndt at følge en liste, for andres lister

For lister, man følger, vises navn på den bruger, der har oprettet listen

![lister desktop](https://user-images.githubusercontent.com/18284484/42375992-d01c3082-811d-11e8-966f-98423a05b1c2.png)

**Comment by KiraH** [comment]
I visningen af lister man følger mangler et Af foran navnet på den der har oprettet listen.

I issuet står desuden at der også skal være en dato for de lister man følger, men det er ikke med i designet, så her skal du nok lige vende med Anders om der skal være en dato eller ikke.

**Comment by YousefMohsen** [comment]
Så vidt jeg kan se, står der at listerne skal _sorteres_ efter dato, men at der skal kun vises navn for den bruger der har oprettet listen. Jeg kan selvfølgelige stadig vende dem Anders når han kommer tilbage:)

Jeg har vist overset at der står "Af" foran navnet. Min fejl.
