### ISSUE TITLE
Gamle offentlige lister spøger

### ISSUE THREAD

**Issue by kfudbc** [DBCDK/content-first#534]
Der laves to kald til backend for at hente lister ud:
- /v1/object/find?type=list&owner=et-owner-id&limit=100000 (brugerens egne lister)
- /v1/object/find?type=list&limit=30 (offentlige lister)

Hvis man fjerner "offentlig" fra en liste, så er det den korrekte opdaterede liste der hentes ud med første request.. Men den gamle offentlige version af listen bliver hentet ud med andet request - og overskriver den korrekte liste.

Dette gælder kun for meget gamle lister - nyoprettede lister har ikke problemet.

**Comment by kfudbc** [comment]
Løsning er vel at slettemarkere et objekt i elvis når det er migreret?

**Comment by BettinaAndersen** [comment]
Tænker at vi som aftalt sletter de gamle lister og starter forfra
