### ISSUE TITLE
datapipeline 2.0: indlæsning af data i content-first

### ISSUE THREAD

**Issue by cboesgaard** [DBCDK/content-first#54]
I issue #44 er der lavet så data fra metakompas etc. bliver skrevet ned i et antal json-filer. Dette sker regelmæssigt i et IS-job (p.t. make-report). Content-first skal bygges og deployes så disse data indlæses. Dette issue omhandler indlæsning af json i content-first.

ACCEPT: content-first kan deployes og startes med data der bygges i make-report (eller tilsvarende job).

**Comment by KiraH** [comment]
Testet OK
