### ISSUE TITLE
Toast komponent

### ISSUE THREAD

**Issue by mtni** [DBCDK/content-first#544]
Det skal være muligt at kunne kalde en Toast komponent som kan give brugeren en bekræftelse på en handling. 

_Design er givet på Dropbox under "Add to list" designet._

---
#### Success kriterie:
Når der f.eks. tilføjes en ny bog til en liste via "Tilføj til Liste" dropdown menuen. Skal der komme en lille besked frem i toppen af telefonen / højre side af desktop skærmen - med en besked/bekræftelse til brugeren om at en bog er blevet tilføjet til den givne liste.

**Comment by KiraH** [comment]
testet OK
