### ISSUE TITLE
ARKETYPE-sektion

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#55]
Under overskriften ”Hvilken typer af forslag vil du se?” får brugeren præsenteret 12 arketyper (I en senere version vil der komme flere arketyper). 
Ingen type er valgt fra start. Det skal være muligt at vælge flere typer på samme tid. 
Ved ”Mouse-over” på en arketype vises udvalgte forfattere, stemningsord og genre, der er knyttet til arketypen, samt et par specifikke titler, som arktetypen kunne have læst. 
For at holde det simpelt, blev det besluttet at funktionaliteten for valg af arketype er:
o	Hvis brugeren vælger en arketype, så markeres tilhørende forfattere, stemningsord og genre i de relevante sektioner.
o     Hvis brugeren fravælger arketypen fjernes kun markeringen af selve arketypen - ikke de relaterede forfatterere osv.

Start-Arketyper: ROMANTIKEREN, HESTEPIGEN, KYNIKEREN, ANAKISTEN, TECH-NØRDEN, FILOSOFFEN, ÆSTETIKEREN, SOCIALREALISTEN, GOTH-TYPEN, HISTORIKEREN, DEN SJOVE, KULTURELSKEREN

Billeder, relationer til forfattere, stemningsord og genre samt design leveres af Læsekompasset.  

Draft-design:
![image](https://user-images.githubusercontent.com/28528078/32499422-d0bd9570-c3d2-11e7-8795-b044ba3b0a3e.png)

**Comment by KiraH** [comment]
Testet OK, ud fra det der kunne laves da billeder, stemningsord, relationer til forfattere ikke var leveret.

Mouseover kunne derfor heller ikke laves. Det opretter jeg en separat US på og lukker denne.
