### ISSUE TITLE
Estimat af ændringer for Læsekompasset ved ændring af Adgangsplatformen 

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#553]
[Analyse af OAuth 2 implementation af Adgangsplatformen.pdf](https://github.com/DBCDK/content-first/files/2282412/Analyse.af.OAuth.2.implementation.af.Adgangsplatformen.pdf)
Hvis løsningen beskrevet i ovenstående analyse implementeres betyder dette også ændringer for Læsekompasset,

Denne userstory går ud på kort at beskrive hvilke ændringer er nødvendige for Læsekompasset og give et estimat på disse

**Comment by vibjerg** [comment]
Opgaver der skal løses:

1. Tilpasning af parametre som sendes til adgangsplatformen. I stedet for token medsendes clientID. 
2. Kald til Hejmdal som udveksler authentication_code med access_token
3. Kald til openplatform som henter brugerinformation.
4. Ved logud sendes user_token med i redirect til adgangsplatformen. 
5. tilretning af tests

Det er mindre ændringer der skal laves i alle opgaverne. Vi har i forvejen alle informationer, og clienter til både hejmdal og adgangsplatformen.

Opgaven forventes at kunne løses indenfor 10 timer.

**Comment by KiraH** [comment]
done
