### ISSUE TITLE
FORFATTER-sektion

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#56]
Under overskriften ”Hvilke forfattere kan du godt lide at læse?” får brugeren præsenteret NN forfattere. Ingen forfattere er valgt fra start, med mindre en arketype er valgt. 
Det skal være muligt at tilføje flere forfattere via en suggest-liste, som består af ~ 1000 forfattere.

Hvis der ikke eksisterer et billede af forfatteren vises et anonymt billede blot med forfatterens navn.

NICE-TO- HAVE: Ved rollover på forfatter vises ekstra information samt forfatterens tre mest populære værker.

Billeder samt design leveres af Læsekompasset.

Draft-design:
![image](https://user-images.githubusercontent.com/28528078/32499764-c24b6886-c3d3-11e7-99c2-e29642a094c3.png)

**Comment by KiraH** [comment]
Testet OK
