### ISSUE TITLE
Søgning på titel og forfatter på søgesiden

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#563]
Første forsøg på en beskrivelse af ønsket funktionalitet på søgesiden i forbindelse med søgning på titel og forfatter.

- Ved indtastning i søgefeltet skal der gives forslag på titler og forfattere, der matcher det indtastede. Se design i issue https://github.com/DBCDK/content-first/issues/478
- Der kan i første omgang kun søges vha suggestions, altså ikke søgning via en indtastet streng.
- Ved tryk på enter uden at der valgt en suggestion, aktiveres den første suggestion. Hvis der ikke er nogen suggestions, sker der ingenting.
- Ved søgning på forfatter vises liste med alle forfatterens bøger.
- Ved søgning på titel vises den valgte bog.
- Der vises op til 10 suggestions, mindst 6 tags, mindst 2 titler og mindst 2 forfattere. Hvs der ikke er suggestions for en af typerne fyldes op med suggestions fra de andre typer hvis muligt.

Hvordan sørger vi for at brugeren ikke kan tilføje tags? 
- Brugeren kan altid tilføje tags. Hvis der tilføjes et tag, når der allerede er søgt på fx titel, fjernes titlen og der vises en toast med mulighed for at fortryde sin indtastning og gå tilbage til den tidligere søgning. "Det er ikke muligt at kombinere søgning på titel eller forfatter med andre filtre, så din søgning er blevet nulstillet. Tryk fortryd hvis du vil tilbage til din tidligere søgning"

Hvordan ser det ud i søgeboksen når man har valgt forfatter/titel.
- Det valgte, fx titel på en bog, vises på sædvanlig vis i et tag med mulighed for at slette tagget.

**Comment by KiraH** [comment]
testet OK
