### ISSUE TITLE
IMPLEMENTERING: Søgning på forfatter eller titel

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#569]
Design er givet af i issue: #563  

Det skal være muligt at søge på forfatter og titel.

Hvis der søges på en forfatter eller titel skal der IKKE (i første omgang) kunne tilføjes tags til søgningen.

Ved søgning på forfatter skal resultatet være en oversigt over bøger af forfatteren.
Ved søgning på titel skal resultatet være en oversigt over bøger med den titel.

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK
