### ISSUE TITLE
STEMNINGS-sektion

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#57]
Under overskriften ”Hvilke stemninger foretrækker du i bøger?” får brugeren præsenteret xx Stemninger. I første version  er det kun overstemninger, der kan vises og vælges.

Billeder, stemninger og design leveres af Læsekompasset.

Draft-design:
![image](https://user-images.githubusercontent.com/28528078/32500046-7f23e35c-c3d4-11e7-9800-69e7e46ca31d.png)

**Comment by KiraH** [comment]
testet OK - ny US oprettet på at få fundet billeder til sektionen.
