### ISSUE TITLE
Forside med bredformat skal have align:bottom i bånd

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#577]
Hvis forsiden for en bog rammer max bredde før den rammer max højde i et bånd, skal den placeres i bunden af boksen, så alle forsider i båndet har samme bundlinie.
Se fx. forsiden til venstre i dette bånd. 

![screenshot 2018-08-21 10 04 06](https://user-images.githubusercontent.com/18284484/44389021-08399100-a52a-11e8-81e9-ff94d4043670.png)

**Comment by KiraH** [comment]
testet OK
