### ISSUE TITLE
Ved overførsel fra huskeliste til liste flyttes kun første værk med

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#578]
Når man fra huskeliste-siden vælger at overføre alle værker i huskelisten til en anden liste, overføres kun det første værk fra huskelisten. Resten af værkerne overføres ikke.

![screenshot 2018-08-21 15 57 32](https://user-images.githubusercontent.com/18284484/44406018-f02e3580-a55a-11e8-816e-3300800efff0.png)

**Comment by KiraH** [comment]
testet done
