### ISSUE TITLE
Manglende konsistens ved valg af ord i ny søg/filter-visning

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#583]
Ved valg af ord/filtre forbliver nogle dropdown åbne efter valg, hvor andre lukker med det samme:
![image](https://user-images.githubusercontent.com/28528078/44516709-14f2ec00-a6c6-11e8-8f28-b31f64752904.png)
(Uafhængig om man kan foretage mere end et valg)

**Løsning aftalt til planning 11.september 2018:
Kun en boks åben af gangen.

Boksen lukker ikke når man har valgt, men står åben så man kan vælge flere ord.**

**Comment by BettinaAndersen** [comment]
@AndersFriisBrodsgaard : Jeg synes det virker meget spøjst at Stemnings-boksen bliver hængende, mens eksempelvis "Handlingens tid" lukker, når man vælger noget. Men efter snak med Morten, er jeg i tvivl om dette er en fejl eller ej?

**Comment by BettinaAndersen** [comment]
Har i øvrigt også funder denne info fra Sarah:
Jeg har lige oplevet at filterboksene (Tempo, stemning m.v.) har lidt for god hukommelse. Når jeg er færdig med at bruge dem og trykker "luk", går tilbage til forsiden og derfra fx vælger et bånd og kommer retur til filtersiden, er de bokse jeg tidligere havde åbne, stadig åbne. Det virker underligt, da jeg jo er i gang med en ny omgang.

**Comment by AndersFriisBrodsgaard** [comment]
Misforståelsen skyldes at jeg havde vist flere åbne bokse i designet (bare for at vise flere forskellige bokse på samme side). Det var egentlig ikke meningen, at de skulle opføre sig forskelligt, men at man selv skal lukke dem, når man er færdig. For at tage hensyn til at man kan have behov for at vælge flere ting i samme filterboks.

**Comment by KiraH** [comment]
testet OK
