### ISSUE TITLE
Huskeliste viser bøger uden forsider forkert

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#584]
Hvis bogen ikke har en forside bliver teksten skubbet til venstre i Huskelisten. Det ser ikke godt ud. Teksten skal være alignet med teksten fra de øvrige bøger uanset at forsiden mangler.
![image](https://user-images.githubusercontent.com/28528078/44517223-62238d80-a6c7-11e8-98a3-1a072f930857.png)

**Comment by kfudbc** [comment]
og titlen skal ikke få i 2 linier - siger funky

**Comment by KiraH** [comment]
testet OK
