### ISSUE TITLE
Man kan ikke lukke huskeliste

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#585]
Hvis man klikker Huskelisten frem kan man ikke lukke den igen?
Testet både i Chrome og Firefox
![image](https://user-images.githubusercontent.com/28528078/44517350-c34b6100-a6c7-11e8-8eda-890d6e020263.png)

**Comment by kfudbc** [comment]
Hvis man trykker på knappen i menuen igen, lukker den så ikke? Gør den hos mig

**Comment by KiraH** [comment]
testet OK
