### ISSUE TITLE
Suggestions ved tilføj bog til liste vises øverst på siden

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#589]
De skal vises under inputfeltet, som man skriver i.

![screenshot 2018-08-24 14 43 00](https://user-images.githubusercontent.com/18284484/44585299-27475580-a7ac-11e8-9631-69e4fc5daa36.png)

**Comment by YousefMohsen** [comment]
Er fixet

**Comment by KiraH** [comment]
testet OK
