### ISSUE TITLE
TOP-sektion

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#59]
I topsektionen skal være: 
o	En grafisk præsentation af hvor godt/meget info brugeren har givet – set i forhold til hvor gode anbefalinger, der kan gives på det basis. (Evt. simplificeret til at starte med. Således at eksempelvis være klik giver 10%, max 100%.) 
o	Brugerens markeringer. Gengives som labels/ikoner.  Hvis mange markeringer er valgt gemmes de ”for mange” i  en 'Se flere'-fold-ud.
o	Et sneak-peek af anbefalinger, som gives på baggrund af brugerens markeringer.

Topsektionen er ”Sticky” og kommer først frem, når brugeren begynder at udfylde sin smagsprofil

Billeder og design leveres af Læsekompasset.
DRAFT-DESIGN:
![image](https://user-images.githubusercontent.com/28528078/32500686-4b10c5c4-c3d6-11e7-96f1-dcb7bdb34e3c.png)

**Comment by KiraH** [comment]
Testet OK, dog kan det først testes om topsektionen er sticky efter der er kommet indhold på forsiden.
