### ISSUE TITLE
Filterside: bugs og smårettelser

### ISSUE THREAD

**Issue by mtni** [DBCDK/content-first#590]
Filtersiden har et par mindre bugs og småfejl som skal rettes:

Suggester:
- [x] Tekst ændres til primary fonten (Montserrat) 
- [x] Markering (u tag) skal være 600 weight
- [x] 2 t'er i input placeholder
- [x] Slet tags med backspace

Topbar: 
- [x] Width calc funktionen fejler ved 'hard refresh' og på mindre skærmstørrelser
- [x] Ændres skærmstørrelsen efter refresh skal width genberegnes så den stadig følger med. 
- [x] "Mine Lister" knappen skal ikke vises på mobil
- [x] MediaQueries skal bruges til at skjule/vise topbar overlayet på mobilen. 
- [x] Topbar overlayet skal forstsat vises over de 600px/mobil
- [x] Inputfelt svæver når søgefeltet er åbent
- [x] Dobbel grøn border
- [x] Tjek alle isMobile - hide med mediaQ hvis det ikke er mobil

Cards: 
- [x] Luk knap (kryds) i cards skal forblive øverst og ikke scrolles væk. 

Container:
- [x] Det skal være op til den enkelte side at justere margen i width (Alle sider skal have 100% width)

**Comment by KiraH** [comment]
done
