### ISSUE TITLE
Forbindelse til i Content-First-siden/Profil-side

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#60]
Ved klik på login på https://content-first.demo.dbc.dk/ skal brugeren – efter verificering af adgangsplatformen - lande på en profilside/underside som viser 

- Mulighed for at oprette smagsprofiler og lister.
- Mulighed for at redigere smagsprofiler
- Mulighed for at vise allerede oprettede lister.

Wireframes og grafik mangler. Nedenstående er blot illustrerende:
![image](https://user-images.githubusercontent.com/28528078/32501170-9b0884ee-c3d7-11e7-9fc0-0d3f20627dee.png)

**Comment by vibjerg** [comment]
Vi mangler noget design på denne side, for at vi lave siden

**Comment by BettinaAndersen** [comment]
Lukkes og erstattes af https://github.com/DBCDK/content-first/issues/173
