### ISSUE TITLE
Oprettelse af liste med typen bogreol skal deaktiveres midlertidigt

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#614]
Der skal tilføjes nogle flere tekstfelter for at understøtte det nye design på bogreolen og foreløbig er disse felter hardcoded. Indtil "Rediger liste"-funktionalitet er implementeret i det nye design med nye felter, skal oprettelse af bogreol-lister deaktiveres, så der ikke opstår forvirring over de hardcodede felter blandt brugerne.

**Comment by KiraH** [comment]
testet OK
