### ISSUE TITLE
"Rediger liste"-funktionalitet på selve listesiden

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#615]
Ejeren af en liste skal have mulighed for at redigere titel, indledning og topbillede på selve listesiden i stedet for på en separat side. Ved redigering vises der:
- en knap til upload af billede
- inputfelt til titel
- inputfelt til indledning

"Gem ændringer"-knappen sidder nederst på siden og er sticky. Ved siden af "Gem"-knappen sidder der en "Sket liste"-knap.

**Comment by KiraH** [comment]
testet done
