### ISSUE TITLE
"Mere"-komponent til visning af kontekstmenu

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#618]
Der skal laves en generisk komponent, som kan åbne og lukke en liste over menupunkter/handlinger relateret til den kontekst, hvor menuen vises. 
Den skal kunne håndtere at blive vist med eller uden tekstlabel, men altid med "Mere"-ikonet
Ved klik på komponenten åbnes en række menupunkter umiddelbart under knapdelen af komponenten. Menupunktern skal kunne placeres så de flugter med enten højre eller venstre del af knapdelen.

**Comment by KiraH** [comment]
testet OK
