### ISSUE TITLE
Brug af communityservice til opbevaring af profil-data

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#62]
Skal opbevare valgte arketyper, forfattere, stemninger og genre.

MANGLER UDDYBENDE BESKRIVELSE

**Comment by jpsecher** [comment]
Som jeg ser det er der tre måder at køre *content-first* og *communityservice* sammen på:

1. Lade *communityservice* køre helt for sig selv, med separat release cyklus, som det oprindelig var tænkt.
1. Lade Jenkins (integration, staging & production) hente, deploye, og starte en *communityservice* dedikeret til *content-first* på samme maskine som *content-first* kører på.
1. Lade *content-first* repo inkludere *communityservice*, enten via NPM eller som et *subrepo*, og så starte en dedikeret *communityservice* op selv.

Valget har betydning for #65, men også hvor kompliceret det er at køre lokalt som udvikler.
De første to måder betyder så at *communityservice* skal mockes af når man kører tests, hvilket nok er en god ting.

**Comment by BettinaAndersen** [comment]
Mangler at gemme data fra grænsefladen i community service

**Comment by KiraH** [comment]
done
