### ISSUE TITLE
Branching af Content-first

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#63]
Den eksisterende https://content-first.demo.dbc.dk/ skal "gemmes" og gerne tildeles en url med versions-nr. så den stadig kan tilgås i nuværende form.

Herefter udbygges med profilen i en næste version.

**Comment by vibjerg** [comment]
Jeg tror vi har besluttet at droppe dette i første omgang og vente og se om det reelt bliver et problem. Lige nu arbejder vi med en profiludvidelse som ikke bør ødelægge noget på resten af content-first, og da de alligevel skal bygges sammen, behøver vi ikke versionering endnu.

**Comment by BettinaAndersen** [comment]
Lukkes da anden løsning er besluttet.
