### ISSUE TITLE
Filterbokse skal ikke forblive "åbne" efter navigering væk fra siden

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#631]
Filterboksene (Tempo, stemning m.v.) har lidt for god hukommelse. Når jeg er færdig med at bruge dem og trykker "luk", går tilbage til forsiden og derfra fx vælger et bånd og kommer retur til filtersiden, er de bokse jeg tidligere havde åbne, stadig åbne.

**Comment by KiraH** [comment]
testet done
