### ISSUE TITLE
Ændringer til filterbokse

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#651]
1. Indhold af bokse

- Skrivestil får indhold = de første 8 termer i vokabularet under fortælleteknik: struktur og skrivestil, dvs.:

[ ]lettilgængeligt sprog
[ ]almindeligt sprog
[ ]krævende sprog
[ ]nøgternt sprog
[ ]detaljeret sprog
[ ]eksperimenterende sprog
[ ]poetisk sprog
[ ]slang

- Skrivestil får nyt navn: Sprog

- Struktur får indhold = de sidste 8 termer i vokabularet under fortælleteknik: struktur og skrivestil, dvs.:

[ ]mange indskudte sætninger
[ ]meget dialog
[ ]mange metaforer
[ ]handling på flere niveauer
[ ]bevidsthedsstrøm
[ ]springer i tid
[ ]åben slutning
[ ]lukket slutning

- Struktur får nyt navn: Skrivestil

2. Ny boks til Fortællerstemme (mellem univers og sprog)

[ ]jeg-fortæller
[ ]3. person-fortæller
[ ]alvidende fortæller
[ ]skiftende synsvinker

3. Sortering af bokse

Stemning > Tempo > Længde > Univers > Fortællerstemme > Sprog > Skrivestil > Handlingens tid

**Comment by KiraH** [comment]
testet done
