### ISSUE TITLE
Opdatering af retningslinjer og verificering af alder

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#652]
I forbindelse med profiloprettelse skal brugeren verificere at være over 13 år

![image](https://user-images.githubusercontent.com/28528078/45370286-36216b00-b5e8-11e8-9c94-25bf82685625.png)

Hvis brugeren ikke hakker af, så skal skal der gives en rød tekst-melding om: "Du skal være over 13 år for at oprette en profil"

Derudover skal retningslinjerne opdateres med nedenstående tekst:

**Om læsekompas.dk**

**Læsekompas.dk er dit inspirationsværktøj til at finde ny læsning**
Læsekompas.dk er bibliotekernes inspirationsværktøj til voksne læsere af skønlitteratur. Alle kan anvende Læsekompasset, men det kræver biblioteks-login, hvis du vil bestille bøger direkte i løsningen.
Læsekompas.dk indeholder et udvalg af skønlitteratur for voksne, der er tilgængeligt til hjemlån eller som e-lån fra folkebiblioteker. Mængden af værker øges over tid og Læsekompasset sigter mod at tilbyde en bred vifte af litteratur. Alle værker indekseres med oplevelsesord for at gøre det muligt for brugere at navigere i litteratur på en ny måde. Der er mulighed for at fremfinde værker og bestille dem direkte i læsekompas.dk.
 
Læsekompas.dk giver også brugere mulighed for at oprette og dele lister med bøger. Man skal være over 13 år for at oprette sig som bruger. 

**Beta-version af læsekompas.dk**
Læsekompas.dk er lanceret som en beta-version. Dette betyder, at vi fortsat tester og justerer. Den version af læsekompas.dk, du oplever er ikke helt færdigudviklet og du vil derfor opleve at løsningen udvikler sig over tid.  

**Hvem står bag?**
Læsekompas.dk er skabt og drives af de danske folkebiblioteker i samarbejde med DBC.

DBC as
Tempovej 7-11
2750 Ballerup
dbc@dbc.dk

**Brugergeneret indhold**
Følgende regler gælder for indlæg og indhold, som du og andre brugere selv lægger på læsekompas.dk. Du er ansvarlig for, at dine indlæg er i overensstemmelse med den til enhver tid gældende lovgivning, herunder at dine indlæg ikke krænker tredjemands rettigheder, eksempelvis ophavsret til tekst og billeder. Egne fotos du uploader til Læsekompasset gøres tilgængelige under en creative commons licens, og du giver læsekompas.dk lov til at mangfoldiggøre, gøre tilgængelig for tredjemand og lave afledte værker.
For alle informationer og alt materiale, du leverer til læsekompas.dk gælder, at du leverer det vederlagsfrit og til fri brug for læsekompas.dk. 
Læsekompas.dk kan ikke kontrollere og er ikke ansvarlig for indhold, som brugerne leverer, og for at du som bruger kan risikere at blive udsat for indhold, som du finder anstødeligt, fejlagtigt eller på anden måde kritisabelt. Du anerkender, at vi som udbyder ikke forhåndsgodkender brugernes indhold, men at vi har retten til uden nærmere begrundelse at fjerne enhver form for indhold, som offentliggøres via læsekompas.dk, hvis det er i modstrid med gældende lovgivning eller ordlyden af de her nævnte betingelser.

**Comment by KiraH** [comment]
done
