### ISSUE TITLE
Rediger profil

### ISSUE THREAD

**Issue by mtni** [DBCDK/content-first#689]
Man kan lige nu ikke redigere sin profil, da boxen "Er du over 13 år" ikke vises på redigersiden. 

"Gamle" profiler har aldrig accepteret at de var over 13 år.

Løsningen:
Boxene `Betingelser` og `Alder` skal vises på redigersiden, hvis de ikke tidligere har været accepteret.

**Comment by KiraH** [comment]
testet OK
