### ISSUE TITLE
Man skal kunne fjerne en bog fra ens egne lister vha dropdown på bogens værkside

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#695]
På værksiden kan man i dropdown'en "Tilføj til liste" se nogle af ens egne lister. Hvis bogen (hvis værkside, man befinder sig på) findes på en af disse lister (fx liste x), er det markeret i dropdown'en. Men hvis man forsøger at fjerne bogen fra liste x ved at vælge den igen fra dropdown'en, bliver bogen ikke fjernet fra listen, den bliver blot flyttet ned som sidste element på listen. 

Det samme gælder for bøger der er tilføjet til en åben liste af en anden bruger. De bøger ses pt. i dropdown'en og det er fint. Men hvis ejeren af listen forsøger at fjerne bogen fra listen vha. dropdown'en på værksiden, sker dette heller ikke. 
Sandsynligvis samme problematik som nævnt ovenfor.

**Comment by hanseriks** [comment]
Fjernelse af titel på egen liste testet og fundet OK.

**Comment by hanseriks** [comment]
Fjernelse af titel på anden liste aftestet  og fundet OK.
