### ISSUE TITLE
Ved opret liste skal tilføj bog disables

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#698]
Når man opretter en ny liste eller redigerer en listes tekst og billede, skal "Tilføj bog"-boksen være dimmet/disabled på samme måde som de andre elementer på siden.

Samtidig skal fejlteksten "Listen skal have en titel" fjernes, og tjekket af listen titel først laves ved "Gem liste".

**Comment by KiraH** [comment]
testet OK
