### ISSUE TITLE
mouseover på arketyper

### ISSUE THREAD

**Issue by KiraH** [DBCDK/content-first#70]
Ved ”Mouse-over” på en arketype vises udvalgte forfattere, stemningsord og genre, der er knyttet til arketypen, samt et par specifikke titler, som arktetypen kunne have læst.

US #69 skal være løst før denne kan implementeres.

**Comment by vibjerg** [comment]
MouseOver effekten er ændret til at man skal klikke på info knappen for at set ekstra info. Er implementeret
