### ISSUE TITLE
Der kan ikke bestilles bøger fra nogen biblioteker

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#716]
Bestilmodalen giver en fejl, se screendump. Er muligvis knyttet til opsætningen på Odsherred Bibliotek, da alle havde samme problem.

![bestil](https://user-images.githubusercontent.com/18284484/46079841-8d9f0980-c198-11e8-9b54-04b3f98216c2.jpg)

**Comment by BettinaAndersen** [comment]
Fikses sandsynligvis med #560
