### ISSUE TITLE
Huskeliste

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#72]
- Tilføj knap til alle værker på Content first - "Tilføj til huskeliste"

- Visning af huskeliste i Content First
    - Når klikker på ikon foldes huskeliste ud. Hvis brugeren klikker på "Se huskeliste", vises Huskeliste-side

- "Huskeliste"side 
   - Hvis brugeren trykker gem, så gemmes huskelisten som en simpel liste under profil, hvis brugeren er logget ind - eller brugeren promptes til at logge ind.

Design og wireframes mangler

**Comment by kfudbc** [comment]
Huskeliste-side har fået sit eget issue #79

**Comment by BettinaAndersen** [comment]
Testet ok
