### ISSUE TITLE
IMPLEMENTERING af Forside

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#720]
Der skal være et forsidebillede med et søgefelt. Feltet skal funktionelt minde om det på søgesiden, dog skal der være forvalgt nogle tags.

Design er givet i #719

**Comment by AndersFriisBrodsgaard** [comment]
Læsekompas-gruppen er glade!

Nogle små kommentarer fra dem - og fra mig:
- langsommere fades mellem billeder
- på brede skærme bliver søgefeltet for bredt
- Hvordan ser det ud, hvis den supplerende tekst (lige over søgefeltet) ikke benyttes?
- Kan der laves rundede hjørner på søgefeltet?
- Mere gennemsigtig baggrund på søgefelt
- outline på søgefelt
- font-weight justeres

Lad os evt. kigge på det sammen.

**Comment by KiraH** [comment]
testet OK
