### ISSUE TITLE
Pin en søgning til min forside (indlogget bruger)

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#731]
Det skal være muligt at pinne en søgning til forsiden. Der skal indsættes en knap øverst på søgesiden til dette formål. Når en bruger pinner en søgning til forsiden, skal der vises et bånd på forsiden for denne bruger, som baserer sig på de tags, den spinnede søgning indeholder.
Båndet skal kun vises, når brugeren er logget ind.

**Comment by BettinaAndersen** [comment]
Lukkes da duplikat af #811
