### ISSUE TITLE
Bogreol: Nynne som liste (bogreol)

### ISSUE THREAD

**Issue by mtni** [DBCDK/content-first#739]
Nynnes liste skal oprettes som bogreol på laesekompas.dk så hendes bogreol kan ses fra forsiden. 

id'et i BookcaseItem på forsiden `<BookcaseItem id={....}/>` skal udskiftes til det nye. 

### OBS! Husk at listen skal være offentlig!

**Comment by BettinaAndersen** [comment]
Testet ok
