### ISSUE TITLE
Oprettelse og visning af simple liste

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#74]
- Fra profilsiden, klikkes på "Ny liste" hvilket leder til  oprettelse af liste. Det skal være muligt at tilføje beskrivelse af listen og beskrivelse af hvert enkelt værk i listen.
Status er sat til offentlig, men kan klikkes over på privat (ingen effekt i første omgang)

- Listen skal kunne vises og gemmes. Titel vises herefter på profilsiden.

**Comment by vibjerg** [comment]
Visning af listen og oversigt på profilside overføres til nye issues

**Comment by KiraH** [comment]
Når man har oprettet en liste og igen klikker på opret ny liste, er felterne udfyldt med informationerne fra den tidligere oprettede liste.

**Comment by KiraH** [comment]
Det ser også ud til at den tidligere liste bliver overskrevet. Når jeg igen står på siden med lister er der nu kun 1 liste - den seneste, selv om jeg har oprettet 2.

**Comment by vibjerg** [comment]
Dette bør være løst med commit 272e81a

**Comment by KiraH** [comment]
Hvis man sætter hak i boksen "Skal listen være offentlig" er der ikke længere hak i boksen når man har gemt listen og derefter går ind på den igen.

**Comment by KiraH** [comment]
testet OK
