### ISSUE TITLE
Tilpasning af bogreol-lister

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/content-first#743]
- [x] På selve listesiden bliver topbilledet "trukket" lidt i bredden. Det skal have samme størrelsesforhold som på en almindelig liste.
- [x] Rediger liste: Labels på prikkerne ved hover skal være mindre og titlen skal vises med Micro - petroleum. Se design her: https://www.dropbox.com/s/22qptouqlubc39g/index.html?dl=0
- [x] Labels skal også vises ved rollover, når man bare ser på listen, både på listeside og på forsiden
- [x] Der skal lades en større version af listebilledet til visning på forsiden. 
- [x] Tidsangivelse på bogreollisten mangler nuller. Der skal stå 15:01 i stedet for 15:1
- [x] Forsidevisningen skal linke til den rigtige liste i mobilversionen. 
- [x] Puls prikkerne renderer/hopper når man redigere en liste
- [x] Facebook knap sidder lidt uheldig på mobil
- [ ] Safari-bug: På listesiden vises den minimerede version af billedet forkert

![screenshot 2018-10-04 14 25 00](https://user-images.githubusercontent.com/18284484/46473751-6e7c2980-c7e1-11e8-82d3-9f9bb3d0ecb7.png)

**Comment by KiraH** [comment]
lukker denne og opretter ny bug
