### ISSUE TITLE
Community Servicen skal kunne indeholde noget adfærds-data

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#76]
Brugerens PID-interaktioner skal gemmes i Community Servicen sammen med tidspunkt og event. Events er minimum klik, tilføj til liste og bestil.
Det skal besluttes om der skal et max antal på eller om der ryddes op på anden vis.
Det skal overvejes om det bliver for tungt at sende ved hver event?  

----

Et bud på tilgangen til dette kunne være:

1. [x] **Adfærdsdata-actions**. Generer actions når brugeren interagerer med pid'er.
2. [x] **Reduxtilstand**. Gem adfærds-data i redux-tilstanden, så den er tilgænglige for det personaliserede bånd.
3. [x] **Gem data**. Gem adfærds-data i det generiske objekt-endpoint
4. [x] **Indlæs data**. Indlæs adfærdsdata når applikationen starter.

## Adfærdsdata-actions

Vi skal huske klik, tilføj til liste, og bestil.
Dette kan gøres ét sted, hvis vi opretter middelware, der lytter efter disse redux-events.
Vi gør allerede noget lignende i forbindelse med logning, i.e. sidst i `src/client/redux/middleware.js`.

De relevante action types er vistnok: 

- `ON_LOCATION_CHANGE` - kaldes når side åbnes, vi kan her tjekke at adressen er en `/værk/$PID`, hvilket svare til, at der er klikket på den pågældende pid/materiale.
- `ON_SHORTLIST_TOGGLE_ELEMENT`/`LIST_TOGGLE_ELEMENT` - tjek at det faktisk er tilføjelse til listen
- `ORDER`

Når en af disse kaldes, kan vi så emitte en ny type adfærdsevent-action, som så kan bruges til at opdatere redux-tilstanden.

## Reduxtilstand

I redux-tilstanden kan vi gemme adfærdsdata, der skal bruges til personaliseret bånd. Eksempelvis de sidste 20 pid'er, der er vist+husket+bestilt. Dette kan implementeres i stil med de øvrige reducers i `src/client/redux`.

## Gem data

Når adfærdsdata i reduxtilstanden opdateres, kan den gemmes i det generiske objektendpoint (i communityservicen). Dette kan gøres med noget middleware, der reagere på om adfærdsdata i reduxtilstanden ændres.
Opdateringer kan eventuelt throttles af hensyn til netværket.

## Indlæs data

Når applikationen starter, kan adfærdsdata indlæses fra det generiske objekt-endpoint til redux-tilstanden. Dette kan eksempelvis blive triggered via user middelware.

**Comment by rasmuserik** [comment]
Har opdelt issuet i forslag til delopgaver, så det er lettere at gå til, - og som vi eventuelt kan arbejde parallelt på.

**Comment by KiraH** [comment]
Ikke til at teste gennem brugergrænsefladen. Jeg lukker den.
