### ISSUE TITLE
Design af kommentarfelt

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#761]
Kommentarfeltet og tilhørende funktionaliteter skal opdateres i forhold til det nye design.
![image](https://user-images.githubusercontent.com/28528078/46937201-e14a9780-d060-11e8-99c7-cb3811dc27ce.png)

**Comment by AndersFriisBrodsgaard** [comment]
Design er her, som en del af designet af listesiden: 
https://www.dropbox.com/sh/twpibu6dnod4hki/AADHpapsz3acqqNs8In4m2hYa?dl=0
