### ISSUE TITLE
PRIO: Overskrifter skal ændres. Must have inden Bogforum

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#762]
- Fjern "En god bog"
- Ændre "Tankevækkende sci-fi" til "tankevækkende fremtidsvisioner". (Kan "fremtid" prioriteres?-senere)
- "Tolkiensque" ændres til "Tolkienesque"
- Ændre "Gotisk uhygge" til "Det var en mørk og stormfuld nat"
- Ændre "Historisk romantik" definitionen til "Historiske romaner (genre, obligatorisk)", "romantisk", "kærlig", "kærlighed"
- Ændre "Vemodige Nordmænd" definitionen "Norge" (Kan "Norge" prioriteres- senere)
- Ændre "Lokalkrimi" til "Hvad sker der bag hækken?":

**Comment by mtni** [comment]
@BettinaAndersen Jeg sklal lige være sikker, skal "Vemodige nordmænd" definition ændres til kun at indeholde tagget norge?
