### ISSUE TITLE
Opsætning af værktøjer til automatisk test af grænseflade og grænsefladekomponenter

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/content-first#77]
Vi skal have testet hovedflows i grænsefladen med seleniumtests + implementeret test af udvalgte React komponenter.

**Comment by jpsecher** [comment]
Måske skulle vi prøve at bruge fx [Phantom](http://phantomjs.org/) for at få testene til at være mere stabile?

**Comment by jacobandresen** [comment]
Har I overvejet jest ? Det er rimeligt fedt . http://facebook.github.io/jest/   :)

**Comment by jpsecher** [comment]
https://spin.atomicobject.com/2017/05/02/react-testing-jest-vs-mocha/

**Comment by kfudbc** [comment]
Jeg har lavet nogle react-komponent tests i https://github.com/DBCDK/content-first/pull/83. Bruger Jest og snapshot-testing, det virker umiddelbart rigtig fint.
Men ja, vi kommer nok ikke udenom nogle selenium-tests af hovedflows, som gerne kører på alle de browsere vi skal understøtte.

**Comment by jacobandresen** [comment]
👍
