### ISSUE TITLE
Det skal være muligt at lave "artikel"-sider

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#773]
Det har vist sig at der flere steder er brug for at kunne vise en "artikel"-side. Eksempelvis en side der forklarer "Om læsekomasset" eller beskriver brug af person-data.

**Comment by vibjerg** [comment]
Jeg synes vi skal overveje at finde en løsning hvor man kan skrive indhold i markdown, så kræver det ikke i samme grad en udvikler for at opdatere teksten.

**Comment by vibjerg** [comment]
Et par projekter det kan være værd at kigge på:
* https://github.com/mdx-js/mdx
* https://github.com/rexxars/react-markdown
Især mdx projektet har jeg et godt øje til, og det er lavet af nogle folk, som plejer at lave nogle meget fornuftige ting.

**Comment by BettinaAndersen** [comment]
Er kun relevant indtil vi får redaktør-funktionalitet

**Comment by BettinaAndersen** [comment]
Lukkes da duplikat af #810
