### ISSUE TITLE
Hero: Visuelle Rettelser

### ISSUE THREAD

**Issue by mtni** [DBCDK/content-first#784]
Rettelser til Hero fra læsekompas gruppen:

- [x] langsommere fades mellem billeder
- [x] på brede skærme bliver søgefeltet for bredt
- [x] Hvordan ser det ud, hvis den supplerende tekst (lige over søgefeltet) ikke benyttes?
- [x] Kan der laves rundede hjørner på søgefeltet?
- [x] Mere gennemsigtig baggrund på søgefelt
- [x] outline på søgefelt
- [ ] font-weight justeres
- [x] slideshow må ikke stoppe, skal fortsætte ved enden (sidste slide)
- [x] baggrundsgradient skal gøres mere gennemsigtig
- [x] tag forbehold for højde på smartphones i landscape format

**Comment by KiraH** [comment]
testet OK
