### ISSUE TITLE
"En god bog"-bånd trin 1: Visning af kriterier og værker

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#8]
Efter klik på "En god bog" fra forsiden vises side med:
- De prevalgte labels. (klik på kryds fjerner disse)
- "Vælg flere"-knap
- Forsider med nuværende værker

NB: Kun valgte "stemning"-labels har effekt.

**Comment by kfudbc** [comment]
frontend-logikken i forhold til at vælge og fjerne labels er lavet. Mulige labels er defineret i en json-struktur som bor på klient-siden. Til at starte med tænker jeg at det er fint de bor her - men på sigt kan de udtrækkes af backend. Selve værk-udtrækning fra backend mangler, det er kun dummy-værker der bliver vist nu.

**Comment by KiraH** [comment]
Udtræk fra backend virker også nu.

Testet OK.
