### ISSUE TITLE
Huskeliste skal gemmes i db

### ISSUE THREAD

**Issue by kfudbc** [DBCDK/content-first#80]
Via endpoint /v1/shortlist.

Hvis brugeren har tilføjet noget til huskeliste inden brugeren er logget ind, skal brugeren informeres om at denne vil blive sammenflettet med den som er gemt for den indloggede bruger.

Herefter tømmes den midlertidige huskeliste fra før brugeren loggede på.

Brugeren kan nu se den samlede liste når han er logget på.

Logger brugeren ud og på igen er listen gemt for brugeren.

**Comment by KiraH** [comment]
testet OK.
