### ISSUE TITLE
Content-first skal være tablet-venlig

### ISSUE THREAD

**Issue by kfudbc** [DBCDK/content-first#84]
Brugeroplevelsen skal være god på både tablet og desktop. P.t. er der kun fokuseret på desktop.
Eksisterende funktionalitet skal gennemgås:
- [ ] bånd der kan scrolles, skal kunne swipes + bøger skal alignes pænere horizontalt.
- [x] Værksiden: beskrivende tekst skal stå til højre for cover (og ikke som nu skubbes nedenunder)
- [x] Huskeliste-knap kommer frem ved hover (hvordan skal det se ud på tablet?) 
- [ ] Filtersiden?
- [ ] Profil-siden + smagsprofil?

**Comment by BettinaAndersen** [comment]
Lad os tage det med i dette sprint, men som en nice-to-have. Det er dog vær at tænke ind ved ny udvikling.

**Comment by AndersFriisBrodsgaard** [comment]
Ikke relevant længere
