### ISSUE TITLE
Systemlister (Læst, Vil læse)

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#86]
Udover huskeliste, skal alle indloggede bruger default have en "Har læst"-liste og en "Vil læse"-liste.
Det skal være muligt at tilføje værker til alle systemlister, dvs. vælge "Husk", "Læst" og "Vil læse".

**Comment by kfudbc** [comment]
Visning af disse lister, hører ikke med til dette issue. Men man kan tilføje til listerne.

**Comment by KiraH** [comment]
testet OK
