### ISSUE TITLE
Service til returnering af læsekompas-anbefalinger 

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/content-first#91]
Der er brug for en service, som i første omgang  kan omsætte stemninger (id/integer), genre (string) og forfattere (string) til anbefalinger(pid’er) inden for Læsekompassets egne værker. Senere vil andre data eksempelvis tidsperioder også være interessante .

**Comment by cboesgaard** [comment]
Der er flere ting i dette:

- datapipeline skal udvides til at genere nødvendig data
- funktionalitet skal integreres i eksisterende recommender eller ny service laves

Planen er at starte med en simpel version med oplæg til api og som giver meningsfyldte men ikke tunede anbefalinger.

**Comment by cboesgaard** [comment]
Planen er at integere nyt endpoint i den eksisterende recommender:
https://github.com/DBCDK/recomole/

Og der er allerede et byggejob der laver model til recommender, med kode i:
https://github.com/DBCDK/mobus

P.t. kører byggejobbet natligt:
https://is.dbc.dk/user/opensearch/my-views/view/recommenders/job/build-content-first-recommender-model/
Men det skal ændres så det trigges af content-first jobbet.

**Comment by cboesgaard** [comment]
I forhold til forfatter, så anvendes de præcise stavemåder der er benyttet i exportTags (fx aa i Lene Kaaberbøl).

**Comment by shmollerup** [comment]
Så er der en service i drift der kan postes til:
http://0.recompass-service.search.prod.mcp1.dbc.dk/recompass
se eventuelt help siden for dokumentation og eksempler:
http://0.recompass-service.search.prod.mcp1.dbc.dk/recompass/help

**Comment by shmollerup** [comment]
Der er nok stadig et udestående med opdateringer af servicen
* hvordan skal byg af service trigges?
* hvordan skal deploy af service trigges?
Både byg og deploy er jenkins jobs

**Comment by shmollerup** [comment]
Der er nu tilføjet lidt error handling - en fejl bliver kastet når man giver servicen en ukendt tag/creator. se evnt. eksemplerne på help siden
