### ISSUE TITLE
Generer genrer ud fra emneord

### ISSUE THREAD

**Issue by KiraH** [DBCDK/content-first#92]
Der skal genereres genrer ud fra de emneord der er tilknyttet de inddaterede værker fra metakompasset.

Emneordene fra værkerne skal gennemgås, og det skal besluttes hvilke der skal fungere som genrer.

**Comment by cboesgaard** [comment]
Genre ligger allerede særsklit, se også https://gist.github.com/12600c53175f92bd05fdddc96a9a9aa4

**Comment by KiraH** [comment]
genrer er pt droppet, lukker denne.
