### ISSUE TITLE
Visning af oversigt over mine lister 

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/content-first#96]
På profilsiden skal det være muligt at se en oversigt over egne lister. 
Der skal desuden være en knap til at oprette nye lister.

[Design mangler]

**Comment by vibjerg** [comment]
affødt af #74

**Comment by BettinaAndersen** [comment]
Del af #173 . Er denne story nødvendig?

**Comment by vibjerg** [comment]
Dette issue bliver erstattet af #173 og skal bare lukkes
