### ISSUE TITLE
Synkronisering af lister grænseflade<->bagende

### ISSUE THREAD

**Issue by kfudbc** [DBCDK/content-first#99]
Pt gemmes alle lister på én gang med et PUT til /v1/lists (og lister man ikke sender med bliver fjernet). Dvs at selvom man laver en lille operation, som at tilføje element til liste, så gemmes alt.

Dette medfører at man kan ende i ubehagelige situationer, hvor data går tabt. Hvis man fx har to browser tabs åbne, kan man i visse tilfælde komme til at gemme et forældet liste-state, så brugeren får slettet nyoprettet data. Eller lister kan komme frem igen, som man allerede har slettet i anden browser.

Mulige løsninger:
- hav liste-operationer på et finere niveau i bagende. (tilføj/fjern elementer osv.)
- brug websockets til synkronisering
- brug af timestamp til at håndtere forældet liste-state

**Comment by jpsecher** [comment]
Mindre granualitet i operationer på lister løser ikke umiddelbart problemer med concurrent update af data.  Problemet vil være der uanset hvor “fint” API’et er.

Men som en meget simpel up-to-date check kan vi lade data have en hash/UUID indbygget og dertil et current-hash endpoint som frontend kan spørge før der laves ændringer.

**Comment by jpsecher** [comment]
Planen er at ændre API således:

- Tilføj endpoint `POST /v1/lists` som bare giver et UUID tilbage, dvs. reserverer et unikt navn for den nye liste.
- Tilføj endpoint `PUT /v1/lists/`*uuid* som opretter/opdaterer en specifik liste.
- Tilføj endpoint `GET /v1/lists/`*uuid* som henter en specifik liste.
- Tilføj endpoint `DELETE /v1/lists/`*uuid* som sletter en specifik liste.
- Slet endpoint `PUT /v1/lists`.

**Comment by BettinaAndersen** [comment]
Done
